// Code generated by Fern. DO NOT EDIT.

package polytomic

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/polytomic/polytomic-go/v24/internal"
	big "math/big"
	time "time"
)

var (
	listEventsRequestFieldOrganizationID = big.NewInt(1 << 0)
	listEventsRequestFieldType           = big.NewInt(1 << 1)
	listEventsRequestFieldStartingAfter  = big.NewInt(1 << 2)
	listEventsRequestFieldEndingBefore   = big.NewInt(1 << 3)
	listEventsRequestFieldLimit          = big.NewInt(1 << 4)
)

type ListEventsRequest struct {
	// Organization to list events for. Only used by system callers; normal and partner callers are always scoped to their own organization.
	OrganizationID *string `json:"-" url:"organization_id,omitempty"`
	// Filter to a single event type. Use GET /api/events_types to list valid values.
	Type *string `json:"-" url:"type,omitempty"`
	// Return events created strictly after this timestamp.
	StartingAfter *time.Time `json:"-" url:"starting_after,omitempty"`
	// Return events created strictly before this timestamp.
	EndingBefore *time.Time `json:"-" url:"ending_before,omitempty"`
	// Maximum number of events to return. Default 10, maximum 100.
	Limit *int `json:"-" url:"limit,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListEventsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetOrganizationID(organizationID *string) {
	l.OrganizationID = organizationID
	l.require(listEventsRequestFieldOrganizationID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetType(type_ *string) {
	l.Type = type_
	l.require(listEventsRequestFieldType)
}

// SetStartingAfter sets the StartingAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetStartingAfter(startingAfter *time.Time) {
	l.StartingAfter = startingAfter
	l.require(listEventsRequestFieldStartingAfter)
}

// SetEndingBefore sets the EndingBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetEndingBefore(endingBefore *time.Time) {
	l.EndingBefore = endingBefore
	l.require(listEventsRequestFieldEndingBefore)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListEventsRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listEventsRequestFieldLimit)
}

var (
	eventingBulkSyncCanceledEventFieldDestinationConnectionID = big.NewInt(1 << 0)
	eventingBulkSyncCanceledEventFieldExecutionID             = big.NewInt(1 << 1)
	eventingBulkSyncCanceledEventFieldOrganizationID          = big.NewInt(1 << 2)
	eventingBulkSyncCanceledEventFieldSourceConnectionID      = big.NewInt(1 << 3)
	eventingBulkSyncCanceledEventFieldSyncID                  = big.NewInt(1 << 4)
	eventingBulkSyncCanceledEventFieldSyncName                = big.NewInt(1 << 5)
)

type EventingBulkSyncCanceledEvent struct {
	DestinationConnectionID *string `json:"destination_connection_id,omitempty" url:"destination_connection_id,omitempty"`
	ExecutionID             *string `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	OrganizationID          *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	SourceConnectionID      *string `json:"source_connection_id,omitempty" url:"source_connection_id,omitempty"`
	SyncID                  *string `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName                *string `json:"sync_name,omitempty" url:"sync_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingBulkSyncCanceledEvent) GetDestinationConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.DestinationConnectionID
}

func (e *EventingBulkSyncCanceledEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingBulkSyncCanceledEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingBulkSyncCanceledEvent) GetSourceConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.SourceConnectionID
}

func (e *EventingBulkSyncCanceledEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingBulkSyncCanceledEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingBulkSyncCanceledEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingBulkSyncCanceledEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetDestinationConnectionID sets the DestinationConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCanceledEvent) SetDestinationConnectionID(destinationConnectionID *string) {
	e.DestinationConnectionID = destinationConnectionID
	e.require(eventingBulkSyncCanceledEventFieldDestinationConnectionID)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCanceledEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingBulkSyncCanceledEventFieldExecutionID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCanceledEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingBulkSyncCanceledEventFieldOrganizationID)
}

// SetSourceConnectionID sets the SourceConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCanceledEvent) SetSourceConnectionID(sourceConnectionID *string) {
	e.SourceConnectionID = sourceConnectionID
	e.require(eventingBulkSyncCanceledEventFieldSourceConnectionID)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCanceledEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingBulkSyncCanceledEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCanceledEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingBulkSyncCanceledEventFieldSyncName)
}

func (e *EventingBulkSyncCanceledEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingBulkSyncCanceledEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingBulkSyncCanceledEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingBulkSyncCanceledEvent) MarshalJSON() ([]byte, error) {
	type embed EventingBulkSyncCanceledEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingBulkSyncCanceledEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingBulkSyncCompletedEventFieldDestinationConnectionID = big.NewInt(1 << 0)
	eventingBulkSyncCompletedEventFieldExecutionID             = big.NewInt(1 << 1)
	eventingBulkSyncCompletedEventFieldOrganizationID          = big.NewInt(1 << 2)
	eventingBulkSyncCompletedEventFieldSourceConnectionID      = big.NewInt(1 << 3)
	eventingBulkSyncCompletedEventFieldSyncID                  = big.NewInt(1 << 4)
	eventingBulkSyncCompletedEventFieldSyncName                = big.NewInt(1 << 5)
	eventingBulkSyncCompletedEventFieldTriggerSource           = big.NewInt(1 << 6)
)

type EventingBulkSyncCompletedEvent struct {
	DestinationConnectionID *string `json:"destination_connection_id,omitempty" url:"destination_connection_id,omitempty"`
	ExecutionID             *string `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	OrganizationID          *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	SourceConnectionID      *string `json:"source_connection_id,omitempty" url:"source_connection_id,omitempty"`
	SyncID                  *string `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName                *string `json:"sync_name,omitempty" url:"sync_name,omitempty"`
	TriggerSource           *string `json:"trigger_source,omitempty" url:"trigger_source,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingBulkSyncCompletedEvent) GetDestinationConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.DestinationConnectionID
}

func (e *EventingBulkSyncCompletedEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingBulkSyncCompletedEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingBulkSyncCompletedEvent) GetSourceConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.SourceConnectionID
}

func (e *EventingBulkSyncCompletedEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingBulkSyncCompletedEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingBulkSyncCompletedEvent) GetTriggerSource() *string {
	if e == nil {
		return nil
	}
	return e.TriggerSource
}

func (e *EventingBulkSyncCompletedEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingBulkSyncCompletedEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetDestinationConnectionID sets the DestinationConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedEvent) SetDestinationConnectionID(destinationConnectionID *string) {
	e.DestinationConnectionID = destinationConnectionID
	e.require(eventingBulkSyncCompletedEventFieldDestinationConnectionID)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingBulkSyncCompletedEventFieldExecutionID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingBulkSyncCompletedEventFieldOrganizationID)
}

// SetSourceConnectionID sets the SourceConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedEvent) SetSourceConnectionID(sourceConnectionID *string) {
	e.SourceConnectionID = sourceConnectionID
	e.require(eventingBulkSyncCompletedEventFieldSourceConnectionID)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingBulkSyncCompletedEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingBulkSyncCompletedEventFieldSyncName)
}

// SetTriggerSource sets the TriggerSource field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedEvent) SetTriggerSource(triggerSource *string) {
	e.TriggerSource = triggerSource
	e.require(eventingBulkSyncCompletedEventFieldTriggerSource)
}

func (e *EventingBulkSyncCompletedEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingBulkSyncCompletedEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingBulkSyncCompletedEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingBulkSyncCompletedEvent) MarshalJSON() ([]byte, error) {
	type embed EventingBulkSyncCompletedEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingBulkSyncCompletedEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingBulkSyncCompletedWithErrorEventFieldDestinationConnectionID = big.NewInt(1 << 0)
	eventingBulkSyncCompletedWithErrorEventFieldExecutionID             = big.NewInt(1 << 1)
	eventingBulkSyncCompletedWithErrorEventFieldOrganizationID          = big.NewInt(1 << 2)
	eventingBulkSyncCompletedWithErrorEventFieldSourceConnectionID      = big.NewInt(1 << 3)
	eventingBulkSyncCompletedWithErrorEventFieldSyncID                  = big.NewInt(1 << 4)
	eventingBulkSyncCompletedWithErrorEventFieldSyncName                = big.NewInt(1 << 5)
	eventingBulkSyncCompletedWithErrorEventFieldTriggerSource           = big.NewInt(1 << 6)
)

type EventingBulkSyncCompletedWithErrorEvent struct {
	DestinationConnectionID *string `json:"destination_connection_id,omitempty" url:"destination_connection_id,omitempty"`
	ExecutionID             *string `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	OrganizationID          *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	SourceConnectionID      *string `json:"source_connection_id,omitempty" url:"source_connection_id,omitempty"`
	SyncID                  *string `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName                *string `json:"sync_name,omitempty" url:"sync_name,omitempty"`
	TriggerSource           *string `json:"trigger_source,omitempty" url:"trigger_source,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingBulkSyncCompletedWithErrorEvent) GetDestinationConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.DestinationConnectionID
}

func (e *EventingBulkSyncCompletedWithErrorEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingBulkSyncCompletedWithErrorEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingBulkSyncCompletedWithErrorEvent) GetSourceConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.SourceConnectionID
}

func (e *EventingBulkSyncCompletedWithErrorEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingBulkSyncCompletedWithErrorEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingBulkSyncCompletedWithErrorEvent) GetTriggerSource() *string {
	if e == nil {
		return nil
	}
	return e.TriggerSource
}

func (e *EventingBulkSyncCompletedWithErrorEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingBulkSyncCompletedWithErrorEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetDestinationConnectionID sets the DestinationConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedWithErrorEvent) SetDestinationConnectionID(destinationConnectionID *string) {
	e.DestinationConnectionID = destinationConnectionID
	e.require(eventingBulkSyncCompletedWithErrorEventFieldDestinationConnectionID)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedWithErrorEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingBulkSyncCompletedWithErrorEventFieldExecutionID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedWithErrorEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingBulkSyncCompletedWithErrorEventFieldOrganizationID)
}

// SetSourceConnectionID sets the SourceConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedWithErrorEvent) SetSourceConnectionID(sourceConnectionID *string) {
	e.SourceConnectionID = sourceConnectionID
	e.require(eventingBulkSyncCompletedWithErrorEventFieldSourceConnectionID)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedWithErrorEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingBulkSyncCompletedWithErrorEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedWithErrorEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingBulkSyncCompletedWithErrorEventFieldSyncName)
}

// SetTriggerSource sets the TriggerSource field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncCompletedWithErrorEvent) SetTriggerSource(triggerSource *string) {
	e.TriggerSource = triggerSource
	e.require(eventingBulkSyncCompletedWithErrorEventFieldTriggerSource)
}

func (e *EventingBulkSyncCompletedWithErrorEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingBulkSyncCompletedWithErrorEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingBulkSyncCompletedWithErrorEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingBulkSyncCompletedWithErrorEvent) MarshalJSON() ([]byte, error) {
	type embed EventingBulkSyncCompletedWithErrorEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingBulkSyncCompletedWithErrorEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingBulkSyncFailedEventFieldDestinationConnectionID = big.NewInt(1 << 0)
	eventingBulkSyncFailedEventFieldError                   = big.NewInt(1 << 1)
	eventingBulkSyncFailedEventFieldExecutionID             = big.NewInt(1 << 2)
	eventingBulkSyncFailedEventFieldOrganizationID          = big.NewInt(1 << 3)
	eventingBulkSyncFailedEventFieldSourceConnectionID      = big.NewInt(1 << 4)
	eventingBulkSyncFailedEventFieldSyncID                  = big.NewInt(1 << 5)
	eventingBulkSyncFailedEventFieldSyncName                = big.NewInt(1 << 6)
	eventingBulkSyncFailedEventFieldTriggerSource           = big.NewInt(1 << 7)
)

type EventingBulkSyncFailedEvent struct {
	DestinationConnectionID *string `json:"destination_connection_id,omitempty" url:"destination_connection_id,omitempty"`
	Error                   *string `json:"error,omitempty" url:"error,omitempty"`
	ExecutionID             *string `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	OrganizationID          *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	SourceConnectionID      *string `json:"source_connection_id,omitempty" url:"source_connection_id,omitempty"`
	SyncID                  *string `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName                *string `json:"sync_name,omitempty" url:"sync_name,omitempty"`
	TriggerSource           *string `json:"trigger_source,omitempty" url:"trigger_source,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingBulkSyncFailedEvent) GetDestinationConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.DestinationConnectionID
}

func (e *EventingBulkSyncFailedEvent) GetError() *string {
	if e == nil {
		return nil
	}
	return e.Error
}

func (e *EventingBulkSyncFailedEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingBulkSyncFailedEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingBulkSyncFailedEvent) GetSourceConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.SourceConnectionID
}

func (e *EventingBulkSyncFailedEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingBulkSyncFailedEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingBulkSyncFailedEvent) GetTriggerSource() *string {
	if e == nil {
		return nil
	}
	return e.TriggerSource
}

func (e *EventingBulkSyncFailedEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingBulkSyncFailedEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetDestinationConnectionID sets the DestinationConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncFailedEvent) SetDestinationConnectionID(destinationConnectionID *string) {
	e.DestinationConnectionID = destinationConnectionID
	e.require(eventingBulkSyncFailedEventFieldDestinationConnectionID)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncFailedEvent) SetError(error_ *string) {
	e.Error = error_
	e.require(eventingBulkSyncFailedEventFieldError)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncFailedEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingBulkSyncFailedEventFieldExecutionID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncFailedEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingBulkSyncFailedEventFieldOrganizationID)
}

// SetSourceConnectionID sets the SourceConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncFailedEvent) SetSourceConnectionID(sourceConnectionID *string) {
	e.SourceConnectionID = sourceConnectionID
	e.require(eventingBulkSyncFailedEventFieldSourceConnectionID)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncFailedEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingBulkSyncFailedEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncFailedEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingBulkSyncFailedEventFieldSyncName)
}

// SetTriggerSource sets the TriggerSource field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncFailedEvent) SetTriggerSource(triggerSource *string) {
	e.TriggerSource = triggerSource
	e.require(eventingBulkSyncFailedEventFieldTriggerSource)
}

func (e *EventingBulkSyncFailedEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingBulkSyncFailedEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingBulkSyncFailedEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingBulkSyncFailedEvent) MarshalJSON() ([]byte, error) {
	type embed EventingBulkSyncFailedEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingBulkSyncFailedEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingBulkSyncRunningEventFieldDestinationConnectionID = big.NewInt(1 << 0)
	eventingBulkSyncRunningEventFieldExecutionID             = big.NewInt(1 << 1)
	eventingBulkSyncRunningEventFieldOrganizationID          = big.NewInt(1 << 2)
	eventingBulkSyncRunningEventFieldSourceConnectionID      = big.NewInt(1 << 3)
	eventingBulkSyncRunningEventFieldSyncID                  = big.NewInt(1 << 4)
	eventingBulkSyncRunningEventFieldSyncName                = big.NewInt(1 << 5)
)

type EventingBulkSyncRunningEvent struct {
	DestinationConnectionID *string `json:"destination_connection_id,omitempty" url:"destination_connection_id,omitempty"`
	ExecutionID             *string `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	OrganizationID          *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	SourceConnectionID      *string `json:"source_connection_id,omitempty" url:"source_connection_id,omitempty"`
	SyncID                  *string `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName                *string `json:"sync_name,omitempty" url:"sync_name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingBulkSyncRunningEvent) GetDestinationConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.DestinationConnectionID
}

func (e *EventingBulkSyncRunningEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingBulkSyncRunningEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingBulkSyncRunningEvent) GetSourceConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.SourceConnectionID
}

func (e *EventingBulkSyncRunningEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingBulkSyncRunningEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingBulkSyncRunningEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingBulkSyncRunningEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetDestinationConnectionID sets the DestinationConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncRunningEvent) SetDestinationConnectionID(destinationConnectionID *string) {
	e.DestinationConnectionID = destinationConnectionID
	e.require(eventingBulkSyncRunningEventFieldDestinationConnectionID)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncRunningEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingBulkSyncRunningEventFieldExecutionID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncRunningEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingBulkSyncRunningEventFieldOrganizationID)
}

// SetSourceConnectionID sets the SourceConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncRunningEvent) SetSourceConnectionID(sourceConnectionID *string) {
	e.SourceConnectionID = sourceConnectionID
	e.require(eventingBulkSyncRunningEventFieldSourceConnectionID)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncRunningEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingBulkSyncRunningEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingBulkSyncRunningEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingBulkSyncRunningEventFieldSyncName)
}

func (e *EventingBulkSyncRunningEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingBulkSyncRunningEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingBulkSyncRunningEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingBulkSyncRunningEvent) MarshalJSON() ([]byte, error) {
	type embed EventingBulkSyncRunningEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingBulkSyncRunningEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingSyncCanceledEventFieldExecutionID        = big.NewInt(1 << 0)
	eventingSyncCanceledEventFieldOrganizationID     = big.NewInt(1 << 1)
	eventingSyncCanceledEventFieldStatus             = big.NewInt(1 << 2)
	eventingSyncCanceledEventFieldSyncID             = big.NewInt(1 << 3)
	eventingSyncCanceledEventFieldSyncName           = big.NewInt(1 << 4)
	eventingSyncCanceledEventFieldTargetConnectionID = big.NewInt(1 << 5)
)

type EventingSyncCanceledEvent struct {
	ExecutionID        *string              `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	OrganizationID     *string              `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	Status             *UtilExecutionStatus `json:"status,omitempty" url:"status,omitempty"`
	SyncID             *string              `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName           *string              `json:"sync_name,omitempty" url:"sync_name,omitempty"`
	TargetConnectionID *string              `json:"target_connection_id,omitempty" url:"target_connection_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingSyncCanceledEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingSyncCanceledEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingSyncCanceledEvent) GetStatus() *UtilExecutionStatus {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *EventingSyncCanceledEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingSyncCanceledEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingSyncCanceledEvent) GetTargetConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.TargetConnectionID
}

func (e *EventingSyncCanceledEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingSyncCanceledEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCanceledEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingSyncCanceledEventFieldExecutionID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCanceledEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingSyncCanceledEventFieldOrganizationID)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCanceledEvent) SetStatus(status *UtilExecutionStatus) {
	e.Status = status
	e.require(eventingSyncCanceledEventFieldStatus)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCanceledEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingSyncCanceledEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCanceledEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingSyncCanceledEventFieldSyncName)
}

// SetTargetConnectionID sets the TargetConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCanceledEvent) SetTargetConnectionID(targetConnectionID *string) {
	e.TargetConnectionID = targetConnectionID
	e.require(eventingSyncCanceledEventFieldTargetConnectionID)
}

func (e *EventingSyncCanceledEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingSyncCanceledEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingSyncCanceledEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingSyncCanceledEvent) MarshalJSON() ([]byte, error) {
	type embed EventingSyncCanceledEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingSyncCanceledEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingSyncCompletedEventFieldDeletedRecords     = big.NewInt(1 << 0)
	eventingSyncCompletedEventFieldErrorCount         = big.NewInt(1 << 1)
	eventingSyncCompletedEventFieldErroredRecords     = big.NewInt(1 << 2)
	eventingSyncCompletedEventFieldExecutionID        = big.NewInt(1 << 3)
	eventingSyncCompletedEventFieldInsertedCount      = big.NewInt(1 << 4)
	eventingSyncCompletedEventFieldInsertedRecords    = big.NewInt(1 << 5)
	eventingSyncCompletedEventFieldOrganizationID     = big.NewInt(1 << 6)
	eventingSyncCompletedEventFieldRecordCount        = big.NewInt(1 << 7)
	eventingSyncCompletedEventFieldStatus             = big.NewInt(1 << 8)
	eventingSyncCompletedEventFieldSyncID             = big.NewInt(1 << 9)
	eventingSyncCompletedEventFieldSyncName           = big.NewInt(1 << 10)
	eventingSyncCompletedEventFieldTargetConnectionID = big.NewInt(1 << 11)
	eventingSyncCompletedEventFieldTotalRecords       = big.NewInt(1 << 12)
	eventingSyncCompletedEventFieldTrigger            = big.NewInt(1 << 13)
	eventingSyncCompletedEventFieldUpdatedCount       = big.NewInt(1 << 14)
	eventingSyncCompletedEventFieldUpdatedRecords     = big.NewInt(1 << 15)
	eventingSyncCompletedEventFieldUpsertedCount      = big.NewInt(1 << 16)
	eventingSyncCompletedEventFieldWarningCount       = big.NewInt(1 << 17)
	eventingSyncCompletedEventFieldWarnings           = big.NewInt(1 << 18)
)

type EventingSyncCompletedEvent struct {
	DeletedRecords     []string             `json:"deleted_records,omitempty" url:"deleted_records,omitempty"`
	ErrorCount         *int                 `json:"error_count,omitempty" url:"error_count,omitempty"`
	ErroredRecords     []string             `json:"errored_records,omitempty" url:"errored_records,omitempty"`
	ExecutionID        *string              `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	InsertedCount      *int                 `json:"inserted_count,omitempty" url:"inserted_count,omitempty"`
	InsertedRecords    []string             `json:"inserted_records,omitempty" url:"inserted_records,omitempty"`
	OrganizationID     *string              `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	RecordCount        *int                 `json:"record_count,omitempty" url:"record_count,omitempty"`
	Status             *UtilExecutionStatus `json:"status,omitempty" url:"status,omitempty"`
	SyncID             *string              `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName           *string              `json:"sync_name,omitempty" url:"sync_name,omitempty"`
	TargetConnectionID *string              `json:"target_connection_id,omitempty" url:"target_connection_id,omitempty"`
	TotalRecords       []string             `json:"total_records,omitempty" url:"total_records,omitempty"`
	Trigger            *string              `json:"trigger,omitempty" url:"trigger,omitempty"`
	UpdatedCount       *int                 `json:"updated_count,omitempty" url:"updated_count,omitempty"`
	UpdatedRecords     []string             `json:"updated_records,omitempty" url:"updated_records,omitempty"`
	UpsertedCount      *int                 `json:"upserted_count,omitempty" url:"upserted_count,omitempty"`
	WarningCount       *int                 `json:"warning_count,omitempty" url:"warning_count,omitempty"`
	Warnings           []string             `json:"warnings,omitempty" url:"warnings,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingSyncCompletedEvent) GetDeletedRecords() []string {
	if e == nil {
		return nil
	}
	return e.DeletedRecords
}

func (e *EventingSyncCompletedEvent) GetErrorCount() *int {
	if e == nil {
		return nil
	}
	return e.ErrorCount
}

func (e *EventingSyncCompletedEvent) GetErroredRecords() []string {
	if e == nil {
		return nil
	}
	return e.ErroredRecords
}

func (e *EventingSyncCompletedEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingSyncCompletedEvent) GetInsertedCount() *int {
	if e == nil {
		return nil
	}
	return e.InsertedCount
}

func (e *EventingSyncCompletedEvent) GetInsertedRecords() []string {
	if e == nil {
		return nil
	}
	return e.InsertedRecords
}

func (e *EventingSyncCompletedEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingSyncCompletedEvent) GetRecordCount() *int {
	if e == nil {
		return nil
	}
	return e.RecordCount
}

func (e *EventingSyncCompletedEvent) GetStatus() *UtilExecutionStatus {
	if e == nil {
		return nil
	}
	return e.Status
}

func (e *EventingSyncCompletedEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingSyncCompletedEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingSyncCompletedEvent) GetTargetConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.TargetConnectionID
}

func (e *EventingSyncCompletedEvent) GetTotalRecords() []string {
	if e == nil {
		return nil
	}
	return e.TotalRecords
}

func (e *EventingSyncCompletedEvent) GetTrigger() *string {
	if e == nil {
		return nil
	}
	return e.Trigger
}

func (e *EventingSyncCompletedEvent) GetUpdatedCount() *int {
	if e == nil {
		return nil
	}
	return e.UpdatedCount
}

func (e *EventingSyncCompletedEvent) GetUpdatedRecords() []string {
	if e == nil {
		return nil
	}
	return e.UpdatedRecords
}

func (e *EventingSyncCompletedEvent) GetUpsertedCount() *int {
	if e == nil {
		return nil
	}
	return e.UpsertedCount
}

func (e *EventingSyncCompletedEvent) GetWarningCount() *int {
	if e == nil {
		return nil
	}
	return e.WarningCount
}

func (e *EventingSyncCompletedEvent) GetWarnings() []string {
	if e == nil {
		return nil
	}
	return e.Warnings
}

func (e *EventingSyncCompletedEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingSyncCompletedEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetDeletedRecords sets the DeletedRecords field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetDeletedRecords(deletedRecords []string) {
	e.DeletedRecords = deletedRecords
	e.require(eventingSyncCompletedEventFieldDeletedRecords)
}

// SetErrorCount sets the ErrorCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetErrorCount(errorCount *int) {
	e.ErrorCount = errorCount
	e.require(eventingSyncCompletedEventFieldErrorCount)
}

// SetErroredRecords sets the ErroredRecords field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetErroredRecords(erroredRecords []string) {
	e.ErroredRecords = erroredRecords
	e.require(eventingSyncCompletedEventFieldErroredRecords)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingSyncCompletedEventFieldExecutionID)
}

// SetInsertedCount sets the InsertedCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetInsertedCount(insertedCount *int) {
	e.InsertedCount = insertedCount
	e.require(eventingSyncCompletedEventFieldInsertedCount)
}

// SetInsertedRecords sets the InsertedRecords field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetInsertedRecords(insertedRecords []string) {
	e.InsertedRecords = insertedRecords
	e.require(eventingSyncCompletedEventFieldInsertedRecords)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingSyncCompletedEventFieldOrganizationID)
}

// SetRecordCount sets the RecordCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetRecordCount(recordCount *int) {
	e.RecordCount = recordCount
	e.require(eventingSyncCompletedEventFieldRecordCount)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetStatus(status *UtilExecutionStatus) {
	e.Status = status
	e.require(eventingSyncCompletedEventFieldStatus)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingSyncCompletedEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingSyncCompletedEventFieldSyncName)
}

// SetTargetConnectionID sets the TargetConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetTargetConnectionID(targetConnectionID *string) {
	e.TargetConnectionID = targetConnectionID
	e.require(eventingSyncCompletedEventFieldTargetConnectionID)
}

// SetTotalRecords sets the TotalRecords field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetTotalRecords(totalRecords []string) {
	e.TotalRecords = totalRecords
	e.require(eventingSyncCompletedEventFieldTotalRecords)
}

// SetTrigger sets the Trigger field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetTrigger(trigger *string) {
	e.Trigger = trigger
	e.require(eventingSyncCompletedEventFieldTrigger)
}

// SetUpdatedCount sets the UpdatedCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetUpdatedCount(updatedCount *int) {
	e.UpdatedCount = updatedCount
	e.require(eventingSyncCompletedEventFieldUpdatedCount)
}

// SetUpdatedRecords sets the UpdatedRecords field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetUpdatedRecords(updatedRecords []string) {
	e.UpdatedRecords = updatedRecords
	e.require(eventingSyncCompletedEventFieldUpdatedRecords)
}

// SetUpsertedCount sets the UpsertedCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetUpsertedCount(upsertedCount *int) {
	e.UpsertedCount = upsertedCount
	e.require(eventingSyncCompletedEventFieldUpsertedCount)
}

// SetWarningCount sets the WarningCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetWarningCount(warningCount *int) {
	e.WarningCount = warningCount
	e.require(eventingSyncCompletedEventFieldWarningCount)
}

// SetWarnings sets the Warnings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedEvent) SetWarnings(warnings []string) {
	e.Warnings = warnings
	e.require(eventingSyncCompletedEventFieldWarnings)
}

func (e *EventingSyncCompletedEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingSyncCompletedEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingSyncCompletedEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingSyncCompletedEvent) MarshalJSON() ([]byte, error) {
	type embed EventingSyncCompletedEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingSyncCompletedEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingSyncCompletedWithErrorsEventFieldError              = big.NewInt(1 << 0)
	eventingSyncCompletedWithErrorsEventFieldExecutionID        = big.NewInt(1 << 1)
	eventingSyncCompletedWithErrorsEventFieldNumberOfErrors     = big.NewInt(1 << 2)
	eventingSyncCompletedWithErrorsEventFieldNumberOfWarnings   = big.NewInt(1 << 3)
	eventingSyncCompletedWithErrorsEventFieldOrganizationID     = big.NewInt(1 << 4)
	eventingSyncCompletedWithErrorsEventFieldSyncID             = big.NewInt(1 << 5)
	eventingSyncCompletedWithErrorsEventFieldSyncName           = big.NewInt(1 << 6)
	eventingSyncCompletedWithErrorsEventFieldTargetConnectionID = big.NewInt(1 << 7)
)

type EventingSyncCompletedWithErrorsEvent struct {
	Error              *string `json:"error,omitempty" url:"error,omitempty"`
	ExecutionID        *string `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	NumberOfErrors     *int    `json:"number_of_errors,omitempty" url:"number_of_errors,omitempty"`
	NumberOfWarnings   *int    `json:"number_of_warnings,omitempty" url:"number_of_warnings,omitempty"`
	OrganizationID     *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	SyncID             *string `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName           *string `json:"sync_name,omitempty" url:"sync_name,omitempty"`
	TargetConnectionID *string `json:"target_connection_id,omitempty" url:"target_connection_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingSyncCompletedWithErrorsEvent) GetError() *string {
	if e == nil {
		return nil
	}
	return e.Error
}

func (e *EventingSyncCompletedWithErrorsEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingSyncCompletedWithErrorsEvent) GetNumberOfErrors() *int {
	if e == nil {
		return nil
	}
	return e.NumberOfErrors
}

func (e *EventingSyncCompletedWithErrorsEvent) GetNumberOfWarnings() *int {
	if e == nil {
		return nil
	}
	return e.NumberOfWarnings
}

func (e *EventingSyncCompletedWithErrorsEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingSyncCompletedWithErrorsEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingSyncCompletedWithErrorsEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingSyncCompletedWithErrorsEvent) GetTargetConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.TargetConnectionID
}

func (e *EventingSyncCompletedWithErrorsEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingSyncCompletedWithErrorsEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedWithErrorsEvent) SetError(error_ *string) {
	e.Error = error_
	e.require(eventingSyncCompletedWithErrorsEventFieldError)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedWithErrorsEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingSyncCompletedWithErrorsEventFieldExecutionID)
}

// SetNumberOfErrors sets the NumberOfErrors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedWithErrorsEvent) SetNumberOfErrors(numberOfErrors *int) {
	e.NumberOfErrors = numberOfErrors
	e.require(eventingSyncCompletedWithErrorsEventFieldNumberOfErrors)
}

// SetNumberOfWarnings sets the NumberOfWarnings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedWithErrorsEvent) SetNumberOfWarnings(numberOfWarnings *int) {
	e.NumberOfWarnings = numberOfWarnings
	e.require(eventingSyncCompletedWithErrorsEventFieldNumberOfWarnings)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedWithErrorsEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingSyncCompletedWithErrorsEventFieldOrganizationID)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedWithErrorsEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingSyncCompletedWithErrorsEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedWithErrorsEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingSyncCompletedWithErrorsEventFieldSyncName)
}

// SetTargetConnectionID sets the TargetConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncCompletedWithErrorsEvent) SetTargetConnectionID(targetConnectionID *string) {
	e.TargetConnectionID = targetConnectionID
	e.require(eventingSyncCompletedWithErrorsEventFieldTargetConnectionID)
}

func (e *EventingSyncCompletedWithErrorsEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingSyncCompletedWithErrorsEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingSyncCompletedWithErrorsEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingSyncCompletedWithErrorsEvent) MarshalJSON() ([]byte, error) {
	type embed EventingSyncCompletedWithErrorsEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingSyncCompletedWithErrorsEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingSyncFailedEventFieldError              = big.NewInt(1 << 0)
	eventingSyncFailedEventFieldExecutionID        = big.NewInt(1 << 1)
	eventingSyncFailedEventFieldOrganizationID     = big.NewInt(1 << 2)
	eventingSyncFailedEventFieldSyncID             = big.NewInt(1 << 3)
	eventingSyncFailedEventFieldSyncName           = big.NewInt(1 << 4)
	eventingSyncFailedEventFieldTargetConnectionID = big.NewInt(1 << 5)
)

type EventingSyncFailedEvent struct {
	Error              *string `json:"error,omitempty" url:"error,omitempty"`
	ExecutionID        *string `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	OrganizationID     *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	SyncID             *string `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName           *string `json:"sync_name,omitempty" url:"sync_name,omitempty"`
	TargetConnectionID *string `json:"target_connection_id,omitempty" url:"target_connection_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingSyncFailedEvent) GetError() *string {
	if e == nil {
		return nil
	}
	return e.Error
}

func (e *EventingSyncFailedEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingSyncFailedEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingSyncFailedEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingSyncFailedEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingSyncFailedEvent) GetTargetConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.TargetConnectionID
}

func (e *EventingSyncFailedEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingSyncFailedEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncFailedEvent) SetError(error_ *string) {
	e.Error = error_
	e.require(eventingSyncFailedEventFieldError)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncFailedEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingSyncFailedEventFieldExecutionID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncFailedEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingSyncFailedEventFieldOrganizationID)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncFailedEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingSyncFailedEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncFailedEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingSyncFailedEventFieldSyncName)
}

// SetTargetConnectionID sets the TargetConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncFailedEvent) SetTargetConnectionID(targetConnectionID *string) {
	e.TargetConnectionID = targetConnectionID
	e.require(eventingSyncFailedEventFieldTargetConnectionID)
}

func (e *EventingSyncFailedEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingSyncFailedEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingSyncFailedEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingSyncFailedEvent) MarshalJSON() ([]byte, error) {
	type embed EventingSyncFailedEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingSyncFailedEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	eventingSyncRunningEventFieldExecutionID        = big.NewInt(1 << 0)
	eventingSyncRunningEventFieldOrganizationID     = big.NewInt(1 << 1)
	eventingSyncRunningEventFieldSyncID             = big.NewInt(1 << 2)
	eventingSyncRunningEventFieldSyncName           = big.NewInt(1 << 3)
	eventingSyncRunningEventFieldTargetConnectionID = big.NewInt(1 << 4)
)

type EventingSyncRunningEvent struct {
	ExecutionID        *string `json:"execution_id,omitempty" url:"execution_id,omitempty"`
	OrganizationID     *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	SyncID             *string `json:"sync_id,omitempty" url:"sync_id,omitempty"`
	SyncName           *string `json:"sync_name,omitempty" url:"sync_name,omitempty"`
	TargetConnectionID *string `json:"target_connection_id,omitempty" url:"target_connection_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventingSyncRunningEvent) GetExecutionID() *string {
	if e == nil {
		return nil
	}
	return e.ExecutionID
}

func (e *EventingSyncRunningEvent) GetOrganizationID() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationID
}

func (e *EventingSyncRunningEvent) GetSyncID() *string {
	if e == nil {
		return nil
	}
	return e.SyncID
}

func (e *EventingSyncRunningEvent) GetSyncName() *string {
	if e == nil {
		return nil
	}
	return e.SyncName
}

func (e *EventingSyncRunningEvent) GetTargetConnectionID() *string {
	if e == nil {
		return nil
	}
	return e.TargetConnectionID
}

func (e *EventingSyncRunningEvent) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EventingSyncRunningEvent) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetExecutionID sets the ExecutionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncRunningEvent) SetExecutionID(executionID *string) {
	e.ExecutionID = executionID
	e.require(eventingSyncRunningEventFieldExecutionID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncRunningEvent) SetOrganizationID(organizationID *string) {
	e.OrganizationID = organizationID
	e.require(eventingSyncRunningEventFieldOrganizationID)
}

// SetSyncID sets the SyncID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncRunningEvent) SetSyncID(syncID *string) {
	e.SyncID = syncID
	e.require(eventingSyncRunningEventFieldSyncID)
}

// SetSyncName sets the SyncName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncRunningEvent) SetSyncName(syncName *string) {
	e.SyncName = syncName
	e.require(eventingSyncRunningEventFieldSyncName)
}

// SetTargetConnectionID sets the TargetConnectionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EventingSyncRunningEvent) SetTargetConnectionID(targetConnectionID *string) {
	e.TargetConnectionID = targetConnectionID
	e.require(eventingSyncRunningEventFieldTargetConnectionID)
}

func (e *EventingSyncRunningEvent) UnmarshalJSON(data []byte) error {
	type unmarshaler EventingSyncRunningEvent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventingSyncRunningEvent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventingSyncRunningEvent) MarshalJSON() ([]byte, error) {
	type embed EventingSyncRunningEvent
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EventingSyncRunningEvent) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	v2EventFieldCreatedAt      = big.NewInt(1 << 0)
	v2EventFieldEvent          = big.NewInt(1 << 1)
	v2EventFieldID             = big.NewInt(1 << 2)
	v2EventFieldOrganizationID = big.NewInt(1 << 3)
	v2EventFieldType           = big.NewInt(1 << 4)
)

type V2Event struct {
	// Timestamp the event was emitted.
	CreatedAt *time.Time      `json:"created_at,omitempty" url:"created_at,omitempty"`
	Event     *V2EventPayload `json:"event,omitempty" url:"event,omitempty"`
	// Unique identifier of the event.
	ID *string `json:"id,omitempty" url:"id,omitempty"`
	// Organization the event belongs to.
	OrganizationID *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	// Event type identifier.
	Type *string `json:"type,omitempty" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V2Event) GetCreatedAt() *time.Time {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *V2Event) GetEvent() *V2EventPayload {
	if v == nil {
		return nil
	}
	return v.Event
}

func (v *V2Event) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V2Event) GetOrganizationID() *string {
	if v == nil {
		return nil
	}
	return v.OrganizationID
}

func (v *V2Event) GetType() *string {
	if v == nil {
		return nil
	}
	return v.Type
}

func (v *V2Event) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V2Event) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2Event) SetCreatedAt(createdAt *time.Time) {
	v.CreatedAt = createdAt
	v.require(v2EventFieldCreatedAt)
}

// SetEvent sets the Event field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2Event) SetEvent(event *V2EventPayload) {
	v.Event = event
	v.require(v2EventFieldEvent)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2Event) SetID(id *string) {
	v.ID = id
	v.require(v2EventFieldID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2Event) SetOrganizationID(organizationID *string) {
	v.OrganizationID = organizationID
	v.require(v2EventFieldOrganizationID)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2Event) SetType(type_ *string) {
	v.Type = type_
	v.require(v2EventFieldType)
}

func (v *V2Event) UnmarshalJSON(data []byte) error {
	type embed V2Event
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
	}{
		embed: embed(*v),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*v = V2Event(unmarshaler.embed)
	v.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V2Event) MarshalJSON() ([]byte, error) {
	type embed V2Event
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
	}{
		embed:     embed(*v),
		CreatedAt: internal.NewOptionalDateTime(v.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V2Event) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

type V2EventPayload struct {
	EventingSyncRunningEvent                *EventingSyncRunningEvent
	EventingSyncCompletedEvent              *EventingSyncCompletedEvent
	EventingSyncFailedEvent                 *EventingSyncFailedEvent
	EventingSyncCanceledEvent               *EventingSyncCanceledEvent
	EventingSyncCompletedWithErrorsEvent    *EventingSyncCompletedWithErrorsEvent
	EventingBulkSyncRunningEvent            *EventingBulkSyncRunningEvent
	EventingBulkSyncCompletedEvent          *EventingBulkSyncCompletedEvent
	EventingBulkSyncCanceledEvent           *EventingBulkSyncCanceledEvent
	EventingBulkSyncCompletedWithErrorEvent *EventingBulkSyncCompletedWithErrorEvent
	EventingBulkSyncFailedEvent             *EventingBulkSyncFailedEvent

	typ string
}

func (v *V2EventPayload) GetEventingSyncRunningEvent() *EventingSyncRunningEvent {
	if v == nil {
		return nil
	}
	return v.EventingSyncRunningEvent
}

func (v *V2EventPayload) GetEventingSyncCompletedEvent() *EventingSyncCompletedEvent {
	if v == nil {
		return nil
	}
	return v.EventingSyncCompletedEvent
}

func (v *V2EventPayload) GetEventingSyncFailedEvent() *EventingSyncFailedEvent {
	if v == nil {
		return nil
	}
	return v.EventingSyncFailedEvent
}

func (v *V2EventPayload) GetEventingSyncCanceledEvent() *EventingSyncCanceledEvent {
	if v == nil {
		return nil
	}
	return v.EventingSyncCanceledEvent
}

func (v *V2EventPayload) GetEventingSyncCompletedWithErrorsEvent() *EventingSyncCompletedWithErrorsEvent {
	if v == nil {
		return nil
	}
	return v.EventingSyncCompletedWithErrorsEvent
}

func (v *V2EventPayload) GetEventingBulkSyncRunningEvent() *EventingBulkSyncRunningEvent {
	if v == nil {
		return nil
	}
	return v.EventingBulkSyncRunningEvent
}

func (v *V2EventPayload) GetEventingBulkSyncCompletedEvent() *EventingBulkSyncCompletedEvent {
	if v == nil {
		return nil
	}
	return v.EventingBulkSyncCompletedEvent
}

func (v *V2EventPayload) GetEventingBulkSyncCanceledEvent() *EventingBulkSyncCanceledEvent {
	if v == nil {
		return nil
	}
	return v.EventingBulkSyncCanceledEvent
}

func (v *V2EventPayload) GetEventingBulkSyncCompletedWithErrorEvent() *EventingBulkSyncCompletedWithErrorEvent {
	if v == nil {
		return nil
	}
	return v.EventingBulkSyncCompletedWithErrorEvent
}

func (v *V2EventPayload) GetEventingBulkSyncFailedEvent() *EventingBulkSyncFailedEvent {
	if v == nil {
		return nil
	}
	return v.EventingBulkSyncFailedEvent
}

func (v *V2EventPayload) UnmarshalJSON(data []byte) error {
	valueEventingSyncRunningEvent := new(EventingSyncRunningEvent)
	if err := json.Unmarshal(data, &valueEventingSyncRunningEvent); err == nil {
		v.typ = "EventingSyncRunningEvent"
		v.EventingSyncRunningEvent = valueEventingSyncRunningEvent
		return nil
	}
	valueEventingSyncCompletedEvent := new(EventingSyncCompletedEvent)
	if err := json.Unmarshal(data, &valueEventingSyncCompletedEvent); err == nil {
		v.typ = "EventingSyncCompletedEvent"
		v.EventingSyncCompletedEvent = valueEventingSyncCompletedEvent
		return nil
	}
	valueEventingSyncFailedEvent := new(EventingSyncFailedEvent)
	if err := json.Unmarshal(data, &valueEventingSyncFailedEvent); err == nil {
		v.typ = "EventingSyncFailedEvent"
		v.EventingSyncFailedEvent = valueEventingSyncFailedEvent
		return nil
	}
	valueEventingSyncCanceledEvent := new(EventingSyncCanceledEvent)
	if err := json.Unmarshal(data, &valueEventingSyncCanceledEvent); err == nil {
		v.typ = "EventingSyncCanceledEvent"
		v.EventingSyncCanceledEvent = valueEventingSyncCanceledEvent
		return nil
	}
	valueEventingSyncCompletedWithErrorsEvent := new(EventingSyncCompletedWithErrorsEvent)
	if err := json.Unmarshal(data, &valueEventingSyncCompletedWithErrorsEvent); err == nil {
		v.typ = "EventingSyncCompletedWithErrorsEvent"
		v.EventingSyncCompletedWithErrorsEvent = valueEventingSyncCompletedWithErrorsEvent
		return nil
	}
	valueEventingBulkSyncRunningEvent := new(EventingBulkSyncRunningEvent)
	if err := json.Unmarshal(data, &valueEventingBulkSyncRunningEvent); err == nil {
		v.typ = "EventingBulkSyncRunningEvent"
		v.EventingBulkSyncRunningEvent = valueEventingBulkSyncRunningEvent
		return nil
	}
	valueEventingBulkSyncCompletedEvent := new(EventingBulkSyncCompletedEvent)
	if err := json.Unmarshal(data, &valueEventingBulkSyncCompletedEvent); err == nil {
		v.typ = "EventingBulkSyncCompletedEvent"
		v.EventingBulkSyncCompletedEvent = valueEventingBulkSyncCompletedEvent
		return nil
	}
	valueEventingBulkSyncCanceledEvent := new(EventingBulkSyncCanceledEvent)
	if err := json.Unmarshal(data, &valueEventingBulkSyncCanceledEvent); err == nil {
		v.typ = "EventingBulkSyncCanceledEvent"
		v.EventingBulkSyncCanceledEvent = valueEventingBulkSyncCanceledEvent
		return nil
	}
	valueEventingBulkSyncCompletedWithErrorEvent := new(EventingBulkSyncCompletedWithErrorEvent)
	if err := json.Unmarshal(data, &valueEventingBulkSyncCompletedWithErrorEvent); err == nil {
		v.typ = "EventingBulkSyncCompletedWithErrorEvent"
		v.EventingBulkSyncCompletedWithErrorEvent = valueEventingBulkSyncCompletedWithErrorEvent
		return nil
	}
	valueEventingBulkSyncFailedEvent := new(EventingBulkSyncFailedEvent)
	if err := json.Unmarshal(data, &valueEventingBulkSyncFailedEvent); err == nil {
		v.typ = "EventingBulkSyncFailedEvent"
		v.EventingBulkSyncFailedEvent = valueEventingBulkSyncFailedEvent
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, v)
}

func (v V2EventPayload) MarshalJSON() ([]byte, error) {
	if v.typ == "EventingSyncRunningEvent" || v.EventingSyncRunningEvent != nil {
		return json.Marshal(v.EventingSyncRunningEvent)
	}
	if v.typ == "EventingSyncCompletedEvent" || v.EventingSyncCompletedEvent != nil {
		return json.Marshal(v.EventingSyncCompletedEvent)
	}
	if v.typ == "EventingSyncFailedEvent" || v.EventingSyncFailedEvent != nil {
		return json.Marshal(v.EventingSyncFailedEvent)
	}
	if v.typ == "EventingSyncCanceledEvent" || v.EventingSyncCanceledEvent != nil {
		return json.Marshal(v.EventingSyncCanceledEvent)
	}
	if v.typ == "EventingSyncCompletedWithErrorsEvent" || v.EventingSyncCompletedWithErrorsEvent != nil {
		return json.Marshal(v.EventingSyncCompletedWithErrorsEvent)
	}
	if v.typ == "EventingBulkSyncRunningEvent" || v.EventingBulkSyncRunningEvent != nil {
		return json.Marshal(v.EventingBulkSyncRunningEvent)
	}
	if v.typ == "EventingBulkSyncCompletedEvent" || v.EventingBulkSyncCompletedEvent != nil {
		return json.Marshal(v.EventingBulkSyncCompletedEvent)
	}
	if v.typ == "EventingBulkSyncCanceledEvent" || v.EventingBulkSyncCanceledEvent != nil {
		return json.Marshal(v.EventingBulkSyncCanceledEvent)
	}
	if v.typ == "EventingBulkSyncCompletedWithErrorEvent" || v.EventingBulkSyncCompletedWithErrorEvent != nil {
		return json.Marshal(v.EventingBulkSyncCompletedWithErrorEvent)
	}
	if v.typ == "EventingBulkSyncFailedEvent" || v.EventingBulkSyncFailedEvent != nil {
		return json.Marshal(v.EventingBulkSyncFailedEvent)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", v)
}

type V2EventPayloadVisitor interface {
	VisitEventingSyncRunningEvent(*EventingSyncRunningEvent) error
	VisitEventingSyncCompletedEvent(*EventingSyncCompletedEvent) error
	VisitEventingSyncFailedEvent(*EventingSyncFailedEvent) error
	VisitEventingSyncCanceledEvent(*EventingSyncCanceledEvent) error
	VisitEventingSyncCompletedWithErrorsEvent(*EventingSyncCompletedWithErrorsEvent) error
	VisitEventingBulkSyncRunningEvent(*EventingBulkSyncRunningEvent) error
	VisitEventingBulkSyncCompletedEvent(*EventingBulkSyncCompletedEvent) error
	VisitEventingBulkSyncCanceledEvent(*EventingBulkSyncCanceledEvent) error
	VisitEventingBulkSyncCompletedWithErrorEvent(*EventingBulkSyncCompletedWithErrorEvent) error
	VisitEventingBulkSyncFailedEvent(*EventingBulkSyncFailedEvent) error
}

func (v *V2EventPayload) Accept(visitor V2EventPayloadVisitor) error {
	if v.typ == "EventingSyncRunningEvent" || v.EventingSyncRunningEvent != nil {
		return visitor.VisitEventingSyncRunningEvent(v.EventingSyncRunningEvent)
	}
	if v.typ == "EventingSyncCompletedEvent" || v.EventingSyncCompletedEvent != nil {
		return visitor.VisitEventingSyncCompletedEvent(v.EventingSyncCompletedEvent)
	}
	if v.typ == "EventingSyncFailedEvent" || v.EventingSyncFailedEvent != nil {
		return visitor.VisitEventingSyncFailedEvent(v.EventingSyncFailedEvent)
	}
	if v.typ == "EventingSyncCanceledEvent" || v.EventingSyncCanceledEvent != nil {
		return visitor.VisitEventingSyncCanceledEvent(v.EventingSyncCanceledEvent)
	}
	if v.typ == "EventingSyncCompletedWithErrorsEvent" || v.EventingSyncCompletedWithErrorsEvent != nil {
		return visitor.VisitEventingSyncCompletedWithErrorsEvent(v.EventingSyncCompletedWithErrorsEvent)
	}
	if v.typ == "EventingBulkSyncRunningEvent" || v.EventingBulkSyncRunningEvent != nil {
		return visitor.VisitEventingBulkSyncRunningEvent(v.EventingBulkSyncRunningEvent)
	}
	if v.typ == "EventingBulkSyncCompletedEvent" || v.EventingBulkSyncCompletedEvent != nil {
		return visitor.VisitEventingBulkSyncCompletedEvent(v.EventingBulkSyncCompletedEvent)
	}
	if v.typ == "EventingBulkSyncCanceledEvent" || v.EventingBulkSyncCanceledEvent != nil {
		return visitor.VisitEventingBulkSyncCanceledEvent(v.EventingBulkSyncCanceledEvent)
	}
	if v.typ == "EventingBulkSyncCompletedWithErrorEvent" || v.EventingBulkSyncCompletedWithErrorEvent != nil {
		return visitor.VisitEventingBulkSyncCompletedWithErrorEvent(v.EventingBulkSyncCompletedWithErrorEvent)
	}
	if v.typ == "EventingBulkSyncFailedEvent" || v.EventingBulkSyncFailedEvent != nil {
		return visitor.VisitEventingBulkSyncFailedEvent(v.EventingBulkSyncFailedEvent)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", v)
}

var (
	v2EventTypesEnvelopeFieldData = big.NewInt(1 << 0)
)

type V2EventTypesEnvelope struct {
	Data []string `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V2EventTypesEnvelope) GetData() []string {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V2EventTypesEnvelope) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V2EventTypesEnvelope) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2EventTypesEnvelope) SetData(data []string) {
	v.Data = data
	v.require(v2EventTypesEnvelopeFieldData)
}

func (v *V2EventTypesEnvelope) UnmarshalJSON(data []byte) error {
	type unmarshaler V2EventTypesEnvelope
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V2EventTypesEnvelope(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V2EventTypesEnvelope) MarshalJSON() ([]byte, error) {
	type embed V2EventTypesEnvelope
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V2EventTypesEnvelope) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v2EventsEnvelopeFieldData = big.NewInt(1 << 0)
)

type V2EventsEnvelope struct {
	Data []*V2Event `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V2EventsEnvelope) GetData() []*V2Event {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V2EventsEnvelope) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V2EventsEnvelope) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2EventsEnvelope) SetData(data []*V2Event) {
	v.Data = data
	v.require(v2EventsEnvelopeFieldData)
}

func (v *V2EventsEnvelope) UnmarshalJSON(data []byte) error {
	type unmarshaler V2EventsEnvelope
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V2EventsEnvelope(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V2EventsEnvelope) MarshalJSON() ([]byte, error) {
	type embed V2EventsEnvelope
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V2EventsEnvelope) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
