// This file was auto-generated by Fern from our API Definition.

package polytomic

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/polytomic/polytomic-go/internal"
)

type V4GlobalErrorSubscribersRequest struct {
	Emails []string `json:"emails,omitempty" url:"-"`
}

type V4GlobalErrorSubscribersResponse struct {
	Emails []string `json:"emails,omitempty" url:"emails,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V4GlobalErrorSubscribersResponse) GetEmails() []string {
	if v == nil {
		return nil
	}
	return v.Emails
}

func (v *V4GlobalErrorSubscribersResponse) GetExtraProperties() map[string]interface{} {
	return v.extraProperties
}

func (v *V4GlobalErrorSubscribersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler V4GlobalErrorSubscribersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V4GlobalErrorSubscribersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V4GlobalErrorSubscribersResponse) String() string {
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
