// Code generated by Fern. DO NOT EDIT.

package polytomic

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/polytomic/polytomic-go/v24/internal"
	big "math/big"
)

var (
	getQueryQueryRunnerRequestFieldPage = big.NewInt(1 << 0)
)

type GetQueryQueryRunnerRequest struct {
	// Opaque pagination token returned in the links.next or links.previous URL of the previous response.
	Page *string `json:"-" url:"page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetQueryQueryRunnerRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetQueryQueryRunnerRequest) SetPage(page *string) {
	g.Page = page
	g.require(getQueryQueryRunnerRequestFieldPage)
}

var (
	v4RunQueryRequestFieldQuery = big.NewInt(1 << 0)
)

type V4RunQueryRequest struct {
	// The query to execute against the connection.
	Query *string `json:"-" url:"query,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V4RunQueryRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryRequest) SetQuery(query *string) {
	v.Query = query
	v.require(v4RunQueryRequestFieldQuery)
}

func (v *V4RunQueryRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler V4RunQueryRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*v = V4RunQueryRequest(body)
	return nil
}

func (v *V4RunQueryRequest) MarshalJSON() ([]byte, error) {
	type embed V4RunQueryRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	v4QueryResultsEnvelopeFieldData  = big.NewInt(1 << 0)
	v4QueryResultsEnvelopeFieldLinks = big.NewInt(1 << 1)
)

type V4QueryResultsEnvelope struct {
	Data  *V4RunQueryResult     `json:"data,omitempty" url:"data,omitempty"`
	Links *V4RunQueryPagination `json:"links,omitempty" url:"links,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V4QueryResultsEnvelope) GetData() *V4RunQueryResult {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V4QueryResultsEnvelope) GetLinks() *V4RunQueryPagination {
	if v == nil {
		return nil
	}
	return v.Links
}

func (v *V4QueryResultsEnvelope) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V4QueryResultsEnvelope) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4QueryResultsEnvelope) SetData(data *V4RunQueryResult) {
	v.Data = data
	v.require(v4QueryResultsEnvelopeFieldData)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4QueryResultsEnvelope) SetLinks(links *V4RunQueryPagination) {
	v.Links = links
	v.require(v4QueryResultsEnvelopeFieldLinks)
}

func (v *V4QueryResultsEnvelope) UnmarshalJSON(data []byte) error {
	type unmarshaler V4QueryResultsEnvelope
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V4QueryResultsEnvelope(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V4QueryResultsEnvelope) MarshalJSON() ([]byte, error) {
	type embed V4QueryResultsEnvelope
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V4QueryResultsEnvelope) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v4RunQueryEnvelopeFieldData = big.NewInt(1 << 0)
)

type V4RunQueryEnvelope struct {
	Data *V4RunQueryResult `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V4RunQueryEnvelope) GetData() *V4RunQueryResult {
	if v == nil {
		return nil
	}
	return v.Data
}

func (v *V4RunQueryEnvelope) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V4RunQueryEnvelope) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryEnvelope) SetData(data *V4RunQueryResult) {
	v.Data = data
	v.require(v4RunQueryEnvelopeFieldData)
}

func (v *V4RunQueryEnvelope) UnmarshalJSON(data []byte) error {
	type unmarshaler V4RunQueryEnvelope
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V4RunQueryEnvelope(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V4RunQueryEnvelope) MarshalJSON() ([]byte, error) {
	type embed V4RunQueryEnvelope
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V4RunQueryEnvelope) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v4RunQueryPaginationFieldNext     = big.NewInt(1 << 0)
	v4RunQueryPaginationFieldPrevious = big.NewInt(1 << 1)
)

type V4RunQueryPagination struct {
	// URL to the next page of results, if available. This may be returned as a host relative path.
	Next *string `json:"next,omitempty" url:"next,omitempty"`
	// URL to the previous page of results, if available. This may be returned as a host relative path.
	Previous *string `json:"previous,omitempty" url:"previous,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V4RunQueryPagination) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V4RunQueryPagination) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

func (v *V4RunQueryPagination) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V4RunQueryPagination) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetNext sets the Next field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryPagination) SetNext(next *string) {
	v.Next = next
	v.require(v4RunQueryPaginationFieldNext)
}

// SetPrevious sets the Previous field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryPagination) SetPrevious(previous *string) {
	v.Previous = previous
	v.require(v4RunQueryPaginationFieldPrevious)
}

func (v *V4RunQueryPagination) UnmarshalJSON(data []byte) error {
	type unmarshaler V4RunQueryPagination
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V4RunQueryPagination(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V4RunQueryPagination) MarshalJSON() ([]byte, error) {
	type embed V4RunQueryPagination
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V4RunQueryPagination) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	v4RunQueryResultFieldCount   = big.NewInt(1 << 0)
	v4RunQueryResultFieldError   = big.NewInt(1 << 1)
	v4RunQueryResultFieldExpires = big.NewInt(1 << 2)
	v4RunQueryResultFieldFields  = big.NewInt(1 << 3)
	v4RunQueryResultFieldID      = big.NewInt(1 << 4)
	v4RunQueryResultFieldResults = big.NewInt(1 << 5)
	v4RunQueryResultFieldStatus  = big.NewInt(1 << 6)
)

type V4RunQueryResult struct {
	// The number of rows returned by the query. This will not be returned until the query completes.
	Count *int `json:"count,omitempty" url:"count,omitempty"`
	// Error message if the query failed.
	Error *string `json:"error,omitempty" url:"error,omitempty"`
	// The time at which the query will expire and be deleted. This will not be returned until the query completes.
	Expires *string `json:"expires,omitempty" url:"expires,omitempty"`
	// The names of the fields returned by the query. This will not be returned until the query completes.
	Fields []string `json:"fields,omitempty" url:"fields,omitempty"`
	// The ID of the query task. Poll GET /api/queries/{id} until the task reaches done or failed to retrieve results.
	ID *string `json:"id,omitempty" url:"id,omitempty"`
	// The query results, returned as an array of objects.
	Results []map[string]any `json:"results,omitempty" url:"results,omitempty"`
	Status  *WorkTaskStatus  `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *V4RunQueryResult) GetCount() *int {
	if v == nil {
		return nil
	}
	return v.Count
}

func (v *V4RunQueryResult) GetError() *string {
	if v == nil {
		return nil
	}
	return v.Error
}

func (v *V4RunQueryResult) GetExpires() *string {
	if v == nil {
		return nil
	}
	return v.Expires
}

func (v *V4RunQueryResult) GetFields() []string {
	if v == nil {
		return nil
	}
	return v.Fields
}

func (v *V4RunQueryResult) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *V4RunQueryResult) GetResults() []map[string]any {
	if v == nil {
		return nil
	}
	return v.Results
}

func (v *V4RunQueryResult) GetStatus() *WorkTaskStatus {
	if v == nil {
		return nil
	}
	return v.Status
}

func (v *V4RunQueryResult) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *V4RunQueryResult) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetCount sets the Count field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryResult) SetCount(count *int) {
	v.Count = count
	v.require(v4RunQueryResultFieldCount)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryResult) SetError(error_ *string) {
	v.Error = error_
	v.require(v4RunQueryResultFieldError)
}

// SetExpires sets the Expires field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryResult) SetExpires(expires *string) {
	v.Expires = expires
	v.require(v4RunQueryResultFieldExpires)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryResult) SetFields(fields []string) {
	v.Fields = fields
	v.require(v4RunQueryResultFieldFields)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryResult) SetID(id *string) {
	v.ID = id
	v.require(v4RunQueryResultFieldID)
}

// SetResults sets the Results field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryResult) SetResults(results []map[string]any) {
	v.Results = results
	v.require(v4RunQueryResultFieldResults)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V4RunQueryResult) SetStatus(status *WorkTaskStatus) {
	v.Status = status
	v.require(v4RunQueryResultFieldStatus)
}

func (v *V4RunQueryResult) UnmarshalJSON(data []byte) error {
	type unmarshaler V4RunQueryResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = V4RunQueryResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *V4RunQueryResult) MarshalJSON() ([]byte, error) {
	type embed V4RunQueryResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *V4RunQueryResult) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
