// Code generated by Fern. DO NOT EDIT.

package polytomic

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/polytomic/polytomic-go/v25/internal"
	big "math/big"
	time "time"
)

var (
	createWebhooksSchemaFieldEndpoint       = big.NewInt(1 << 0)
	createWebhooksSchemaFieldOrganizationID = big.NewInt(1 << 1)
	createWebhooksSchemaFieldSecret         = big.NewInt(1 << 2)
)

type CreateWebhooksSchema struct {
	Endpoint       string  `json:"endpoint" url:"-"`
	OrganizationID *string `json:"organization_id,omitempty" url:"-"`
	Secret         string  `json:"secret" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateWebhooksSchema) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetEndpoint sets the Endpoint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWebhooksSchema) SetEndpoint(endpoint string) {
	c.Endpoint = endpoint
	c.require(createWebhooksSchemaFieldEndpoint)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWebhooksSchema) SetOrganizationID(organizationID *string) {
	c.OrganizationID = organizationID
	c.require(createWebhooksSchemaFieldOrganizationID)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWebhooksSchema) SetSecret(secret string) {
	c.Secret = secret
	c.require(createWebhooksSchemaFieldSecret)
}

func (c *CreateWebhooksSchema) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateWebhooksSchema
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateWebhooksSchema(body)
	return nil
}

func (c *CreateWebhooksSchema) MarshalJSON() ([]byte, error) {
	type embed CreateWebhooksSchema
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	updateWebhooksSchemaFieldEndpoint       = big.NewInt(1 << 0)
	updateWebhooksSchemaFieldOrganizationID = big.NewInt(1 << 1)
	updateWebhooksSchemaFieldSecret         = big.NewInt(1 << 2)
)

type UpdateWebhooksSchema struct {
	Endpoint       string  `json:"endpoint" url:"-"`
	OrganizationID *string `json:"organization_id,omitempty" url:"-"`
	Secret         string  `json:"secret" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateWebhooksSchema) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetEndpoint sets the Endpoint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateWebhooksSchema) SetEndpoint(endpoint string) {
	u.Endpoint = endpoint
	u.require(updateWebhooksSchemaFieldEndpoint)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateWebhooksSchema) SetOrganizationID(organizationID *string) {
	u.OrganizationID = organizationID
	u.require(updateWebhooksSchemaFieldOrganizationID)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateWebhooksSchema) SetSecret(secret string) {
	u.Secret = secret
	u.require(updateWebhooksSchemaFieldSecret)
}

func (u *UpdateWebhooksSchema) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateWebhooksSchema
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateWebhooksSchema(body)
	return nil
}

func (u *UpdateWebhooksSchema) MarshalJSON() ([]byte, error) {
	type embed UpdateWebhooksSchema
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	webhookFieldCreatedAt      = big.NewInt(1 << 0)
	webhookFieldDisabled       = big.NewInt(1 << 1)
	webhookFieldEndpoint       = big.NewInt(1 << 2)
	webhookFieldID             = big.NewInt(1 << 3)
	webhookFieldOrganizationID = big.NewInt(1 << 4)
	webhookFieldSecret         = big.NewInt(1 << 5)
)

type Webhook struct {
	CreatedAt      *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	Disabled       *bool      `json:"disabled,omitempty" url:"disabled,omitempty"`
	Endpoint       *string    `json:"endpoint,omitempty" url:"endpoint,omitempty"`
	ID             *string    `json:"id,omitempty" url:"id,omitempty"`
	OrganizationID *string    `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	Secret         *string    `json:"secret,omitempty" url:"secret,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *Webhook) GetCreatedAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.CreatedAt
}

func (w *Webhook) GetDisabled() *bool {
	if w == nil {
		return nil
	}
	return w.Disabled
}

func (w *Webhook) GetEndpoint() *string {
	if w == nil {
		return nil
	}
	return w.Endpoint
}

func (w *Webhook) GetID() *string {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *Webhook) GetOrganizationID() *string {
	if w == nil {
		return nil
	}
	return w.OrganizationID
}

func (w *Webhook) GetSecret() *string {
	if w == nil {
		return nil
	}
	return w.Secret
}

func (w *Webhook) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *Webhook) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Webhook) SetCreatedAt(createdAt *time.Time) {
	w.CreatedAt = createdAt
	w.require(webhookFieldCreatedAt)
}

// SetDisabled sets the Disabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Webhook) SetDisabled(disabled *bool) {
	w.Disabled = disabled
	w.require(webhookFieldDisabled)
}

// SetEndpoint sets the Endpoint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Webhook) SetEndpoint(endpoint *string) {
	w.Endpoint = endpoint
	w.require(webhookFieldEndpoint)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Webhook) SetID(id *string) {
	w.ID = id
	w.require(webhookFieldID)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Webhook) SetOrganizationID(organizationID *string) {
	w.OrganizationID = organizationID
	w.require(webhookFieldOrganizationID)
}

// SetSecret sets the Secret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *Webhook) SetSecret(secret *string) {
	w.Secret = secret
	w.require(webhookFieldSecret)
}

func (w *Webhook) UnmarshalJSON(data []byte) error {
	type embed Webhook
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = Webhook(unmarshaler.embed)
	w.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *Webhook) MarshalJSON() ([]byte, error) {
	type embed Webhook
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at,omitempty"`
	}{
		embed:     embed(*w),
		CreatedAt: internal.NewOptionalDateTime(w.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *Webhook) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	webhookEnvelopeFieldData = big.NewInt(1 << 0)
)

type WebhookEnvelope struct {
	Data *Webhook `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookEnvelope) GetData() *Webhook {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WebhookEnvelope) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookEnvelope) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookEnvelope) SetData(data *Webhook) {
	w.Data = data
	w.require(webhookEnvelopeFieldData)
}

func (w *WebhookEnvelope) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookEnvelope
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookEnvelope(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookEnvelope) MarshalJSON() ([]byte, error) {
	type embed WebhookEnvelope
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookEnvelope) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	webhookListEnvelopeFieldData = big.NewInt(1 << 0)
)

type WebhookListEnvelope struct {
	Data []*Webhook `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WebhookListEnvelope) GetData() []*Webhook {
	if w == nil {
		return nil
	}
	return w.Data
}

func (w *WebhookListEnvelope) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WebhookListEnvelope) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WebhookListEnvelope) SetData(data []*Webhook) {
	w.Data = data
	w.require(webhookListEnvelopeFieldData)
}

func (w *WebhookListEnvelope) UnmarshalJSON(data []byte) error {
	type unmarshaler WebhookListEnvelope
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WebhookListEnvelope(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WebhookListEnvelope) MarshalJSON() ([]byte, error) {
	type embed WebhookListEnvelope
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WebhookListEnvelope) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}
