// Code generated by Fern. DO NOT EDIT.

package polytomic

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersCreateWebhooksSchema(t *testing.T) {
	t.Run("SetEndpoint", func(t *testing.T) {
		obj := &CreateWebhooksSchema{}
		var fernTestValueEndpoint string
		obj.SetEndpoint(fernTestValueEndpoint)
		assert.Equal(t, fernTestValueEndpoint, obj.Endpoint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrganizationID", func(t *testing.T) {
		obj := &CreateWebhooksSchema{}
		var fernTestValueOrganizationID *string
		obj.SetOrganizationID(fernTestValueOrganizationID)
		assert.Equal(t, fernTestValueOrganizationID, obj.OrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSecret", func(t *testing.T) {
		obj := &CreateWebhooksSchema{}
		var fernTestValueSecret string
		obj.SetSecret(fernTestValueSecret)
		assert.Equal(t, fernTestValueSecret, obj.Secret)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateWebhooksSchema(t *testing.T) {
	t.Run("SetEndpoint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhooksSchema{}
		var fernTestValueEndpoint string

		// Act
		obj.SetEndpoint(fernTestValueEndpoint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhooksSchema{}
		var fernTestValueOrganizationID *string

		// Act
		obj.SetOrganizationID(fernTestValueOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSecret_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateWebhooksSchema{}
		var fernTestValueSecret string

		// Act
		obj.SetSecret(fernTestValueSecret)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhooksListDeliveriesRequest(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEventID", func(t *testing.T) {
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValueEventID *string
		obj.SetEventID(fernTestValueEventID)
		assert.Equal(t, fernTestValueEventID, obj.EventID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStart", func(t *testing.T) {
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValueStart *time.Time
		obj.SetStart(fernTestValueStart)
		assert.Equal(t, fernTestValueStart, obj.Start)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEnd", func(t *testing.T) {
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValueEnd *time.Time
		obj.SetEnd(fernTestValueEnd)
		assert.Equal(t, fernTestValueEnd, obj.End)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageToken", func(t *testing.T) {
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValuePageToken *string
		obj.SetPageToken(fernTestValuePageToken)
		assert.Equal(t, fernTestValuePageToken, obj.PageToken)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitWebhooksListDeliveriesRequest(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEventID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValueEventID *string

		// Act
		obj.SetEventID(fernTestValueEventID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStart_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValueStart *time.Time

		// Act
		obj.SetStart(fernTestValueStart)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEnd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValueEnd *time.Time

		// Act
		obj.SetEnd(fernTestValueEnd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhooksListDeliveriesRequest{}
		var fernTestValuePageToken *string

		// Act
		obj.SetPageToken(fernTestValuePageToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateWebhooksSchema(t *testing.T) {
	t.Run("SetEndpoint", func(t *testing.T) {
		obj := &UpdateWebhooksSchema{}
		var fernTestValueEndpoint string
		obj.SetEndpoint(fernTestValueEndpoint)
		assert.Equal(t, fernTestValueEndpoint, obj.Endpoint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrganizationID", func(t *testing.T) {
		obj := &UpdateWebhooksSchema{}
		var fernTestValueOrganizationID *string
		obj.SetOrganizationID(fernTestValueOrganizationID)
		assert.Equal(t, fernTestValueOrganizationID, obj.OrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSecret", func(t *testing.T) {
		obj := &UpdateWebhooksSchema{}
		var fernTestValueSecret string
		obj.SetSecret(fernTestValueSecret)
		assert.Equal(t, fernTestValueSecret, obj.Secret)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpdateWebhooksSchema(t *testing.T) {
	t.Run("SetEndpoint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhooksSchema{}
		var fernTestValueEndpoint string

		// Act
		obj.SetEndpoint(fernTestValueEndpoint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhooksSchema{}
		var fernTestValueOrganizationID *string

		// Act
		obj.SetOrganizationID(fernTestValueOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSecret_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateWebhooksSchema{}
		var fernTestValueSecret string

		// Act
		obj.SetSecret(fernTestValueSecret)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhook(t *testing.T) {
	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &Webhook{}
		var fernTestValueCreatedAt *time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisabled", func(t *testing.T) {
		obj := &Webhook{}
		var fernTestValueDisabled *bool
		obj.SetDisabled(fernTestValueDisabled)
		assert.Equal(t, fernTestValueDisabled, obj.Disabled)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisabledAt", func(t *testing.T) {
		obj := &Webhook{}
		var fernTestValueDisabledAt *time.Time
		obj.SetDisabledAt(fernTestValueDisabledAt)
		assert.Equal(t, fernTestValueDisabledAt, obj.DisabledAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisabledReason", func(t *testing.T) {
		obj := &Webhook{}
		var fernTestValueDisabledReason *string
		obj.SetDisabledReason(fernTestValueDisabledReason)
		assert.Equal(t, fernTestValueDisabledReason, obj.DisabledReason)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpoint", func(t *testing.T) {
		obj := &Webhook{}
		var fernTestValueEndpoint *string
		obj.SetEndpoint(fernTestValueEndpoint)
		assert.Equal(t, fernTestValueEndpoint, obj.Endpoint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &Webhook{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrganizationID", func(t *testing.T) {
		obj := &Webhook{}
		var fernTestValueOrganizationID *string
		obj.SetOrganizationID(fernTestValueOrganizationID)
		assert.Equal(t, fernTestValueOrganizationID, obj.OrganizationID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSecret", func(t *testing.T) {
		obj := &Webhook{}
		var fernTestValueSecret *string
		obj.SetSecret(fernTestValueSecret)
		assert.Equal(t, fernTestValueSecret, obj.Secret)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhook(t *testing.T) {
	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var expected *time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		obj.CreatedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetCreatedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetDisabled", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var expected *bool
		obj.Disabled = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisabled(), "getter should return the property value")
	})

	t.Run("GetDisabled_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		obj.Disabled = nil

		// Act & Assert
		assert.Nil(t, obj.GetDisabled(), "getter should return nil when property is nil")
	})

	t.Run("GetDisabled_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisabled() // Should return zero value
	})

	t.Run("GetDisabledAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var expected *time.Time
		obj.DisabledAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisabledAt(), "getter should return the property value")
	})

	t.Run("GetDisabledAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		obj.DisabledAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetDisabledAt(), "getter should return nil when property is nil")
	})

	t.Run("GetDisabledAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisabledAt() // Should return zero value
	})

	t.Run("GetDisabledReason", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var expected *string
		obj.DisabledReason = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisabledReason(), "getter should return the property value")
	})

	t.Run("GetDisabledReason_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		obj.DisabledReason = nil

		// Act & Assert
		assert.Nil(t, obj.GetDisabledReason(), "getter should return nil when property is nil")
	})

	t.Run("GetDisabledReason_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisabledReason() // Should return zero value
	})

	t.Run("GetEndpoint", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var expected *string
		obj.Endpoint = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEndpoint(), "getter should return the property value")
	})

	t.Run("GetEndpoint_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		obj.Endpoint = nil

		// Act & Assert
		assert.Nil(t, obj.GetEndpoint(), "getter should return nil when property is nil")
	})

	t.Run("GetEndpoint_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEndpoint() // Should return zero value
	})

	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetOrganizationID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var expected *string
		obj.OrganizationID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrganizationID(), "getter should return the property value")
	})

	t.Run("GetOrganizationID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		obj.OrganizationID = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrganizationID(), "getter should return nil when property is nil")
	})

	t.Run("GetOrganizationID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrganizationID() // Should return zero value
	})

	t.Run("GetSecret", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var expected *string
		obj.Secret = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSecret(), "getter should return the property value")
	})

	t.Run("GetSecret_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		obj.Secret = nil

		// Act & Assert
		assert.Nil(t, obj.GetSecret(), "getter should return nil when property is nil")
	})

	t.Run("GetSecret_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSecret() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhook(t *testing.T) {
	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var fernTestValueCreatedAt *time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisabled_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var fernTestValueDisabled *bool

		// Act
		obj.SetDisabled(fernTestValueDisabled)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisabledAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var fernTestValueDisabledAt *time.Time

		// Act
		obj.SetDisabledAt(fernTestValueDisabledAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisabledReason_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var fernTestValueDisabledReason *string

		// Act
		obj.SetDisabledReason(fernTestValueDisabledReason)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpoint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var fernTestValueEndpoint *string

		// Act
		obj.SetEndpoint(fernTestValueEndpoint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrganizationID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var fernTestValueOrganizationID *string

		// Act
		obj.SetOrganizationID(fernTestValueOrganizationID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSecret_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}
		var fernTestValueSecret *string

		// Act
		obj.SetSecret(fernTestValueSecret)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookDeliveriesEnvelope(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &WebhookDeliveriesEnvelope{}
		var fernTestValueData []*WebhookDelivery
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPagination", func(t *testing.T) {
		obj := &WebhookDeliveriesEnvelope{}
		var fernTestValuePagination *PaginationDetails
		obj.SetPagination(fernTestValuePagination)
		assert.Equal(t, fernTestValuePagination, obj.Pagination)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookDeliveriesEnvelope(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDeliveriesEnvelope{}
		var expected []*WebhookDelivery
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDeliveriesEnvelope{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDeliveriesEnvelope
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetPagination", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDeliveriesEnvelope{}
		var expected *PaginationDetails
		obj.Pagination = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPagination(), "getter should return the property value")
	})

	t.Run("GetPagination_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDeliveriesEnvelope{}
		obj.Pagination = nil

		// Act & Assert
		assert.Nil(t, obj.GetPagination(), "getter should return nil when property is nil")
	})

	t.Run("GetPagination_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDeliveriesEnvelope
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPagination() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookDeliveriesEnvelope(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDeliveriesEnvelope{}
		var fernTestValueData []*WebhookDelivery

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPagination_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDeliveriesEnvelope{}
		var fernTestValuePagination *PaginationDetails

		// Act
		obj.SetPagination(fernTestValuePagination)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookDelivery(t *testing.T) {
	t.Run("SetAttemptedAt", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueAttemptedAt *time.Time
		obj.SetAttemptedAt(fernTestValueAttemptedAt)
		assert.Equal(t, fernTestValueAttemptedAt, obj.AttemptedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDurationMs", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueDurationMs *int
		obj.SetDurationMs(fernTestValueDurationMs)
		assert.Equal(t, fernTestValueDurationMs, obj.DurationMs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetError", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueError *string
		obj.SetError(fernTestValueError)
		assert.Equal(t, fernTestValueError, obj.Error)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetErrorKind", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueErrorKind *string
		obj.SetErrorKind(fernTestValueErrorKind)
		assert.Equal(t, fernTestValueErrorKind, obj.ErrorKind)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEventID", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueEventID *string
		obj.SetEventID(fernTestValueEventID)
		assert.Equal(t, fernTestValueEventID, obj.EventID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEventType", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueEventType *string
		obj.SetEventType(fernTestValueEventType)
		assert.Equal(t, fernTestValueEventType, obj.EventType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResponseBody", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueResponseBody *string
		obj.SetResponseBody(fernTestValueResponseBody)
		assert.Equal(t, fernTestValueResponseBody, obj.ResponseBody)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatusCode", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueStatusCode *int
		obj.SetStatusCode(fernTestValueStatusCode)
		assert.Equal(t, fernTestValueStatusCode, obj.StatusCode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &WebhookDelivery{}
		var fernTestValueSuccess *bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookDelivery(t *testing.T) {
	t.Run("GetAttemptedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *time.Time
		obj.AttemptedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAttemptedAt(), "getter should return the property value")
	})

	t.Run("GetAttemptedAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.AttemptedAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetAttemptedAt(), "getter should return nil when property is nil")
	})

	t.Run("GetAttemptedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAttemptedAt() // Should return zero value
	})

	t.Run("GetDurationMs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *int
		obj.DurationMs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDurationMs(), "getter should return the property value")
	})

	t.Run("GetDurationMs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.DurationMs = nil

		// Act & Assert
		assert.Nil(t, obj.GetDurationMs(), "getter should return nil when property is nil")
	})

	t.Run("GetDurationMs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDurationMs() // Should return zero value
	})

	t.Run("GetError", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *string
		obj.Error = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetError(), "getter should return the property value")
	})

	t.Run("GetError_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.Error = nil

		// Act & Assert
		assert.Nil(t, obj.GetError(), "getter should return nil when property is nil")
	})

	t.Run("GetError_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetError() // Should return zero value
	})

	t.Run("GetErrorKind", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *string
		obj.ErrorKind = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetErrorKind(), "getter should return the property value")
	})

	t.Run("GetErrorKind_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.ErrorKind = nil

		// Act & Assert
		assert.Nil(t, obj.GetErrorKind(), "getter should return nil when property is nil")
	})

	t.Run("GetErrorKind_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetErrorKind() // Should return zero value
	})

	t.Run("GetEventID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *string
		obj.EventID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEventID(), "getter should return the property value")
	})

	t.Run("GetEventID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.EventID = nil

		// Act & Assert
		assert.Nil(t, obj.GetEventID(), "getter should return nil when property is nil")
	})

	t.Run("GetEventID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEventID() // Should return zero value
	})

	t.Run("GetEventType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *string
		obj.EventType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEventType(), "getter should return the property value")
	})

	t.Run("GetEventType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.EventType = nil

		// Act & Assert
		assert.Nil(t, obj.GetEventType(), "getter should return nil when property is nil")
	})

	t.Run("GetEventType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEventType() // Should return zero value
	})

	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetResponseBody", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *string
		obj.ResponseBody = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResponseBody(), "getter should return the property value")
	})

	t.Run("GetResponseBody_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.ResponseBody = nil

		// Act & Assert
		assert.Nil(t, obj.GetResponseBody(), "getter should return nil when property is nil")
	})

	t.Run("GetResponseBody_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResponseBody() // Should return zero value
	})

	t.Run("GetStatusCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *int
		obj.StatusCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatusCode(), "getter should return the property value")
	})

	t.Run("GetStatusCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.StatusCode = nil

		// Act & Assert
		assert.Nil(t, obj.GetStatusCode(), "getter should return nil when property is nil")
	})

	t.Run("GetStatusCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatusCode() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var expected *bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		obj.Success = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccess(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookDelivery(t *testing.T) {
	t.Run("SetAttemptedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueAttemptedAt *time.Time

		// Act
		obj.SetAttemptedAt(fernTestValueAttemptedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDurationMs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueDurationMs *int

		// Act
		obj.SetDurationMs(fernTestValueDurationMs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueError *string

		// Act
		obj.SetError(fernTestValueError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetErrorKind_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueErrorKind *string

		// Act
		obj.SetErrorKind(fernTestValueErrorKind)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEventID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueEventID *string

		// Act
		obj.SetEventID(fernTestValueEventID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEventType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueEventType *string

		// Act
		obj.SetEventType(fernTestValueEventType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResponseBody_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueResponseBody *string

		// Act
		obj.SetResponseBody(fernTestValueResponseBody)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatusCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueStatusCode *int

		// Act
		obj.SetStatusCode(fernTestValueStatusCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}
		var fernTestValueSuccess *bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookEnvelope(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &WebhookEnvelope{}
		var fernTestValueData *Webhook
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookEnvelope(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookEnvelope{}
		var expected *Webhook
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookEnvelope{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookEnvelope
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookEnvelope(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookEnvelope{}
		var fernTestValueData *Webhook

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersWebhookListEnvelope(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &WebhookListEnvelope{}
		var fernTestValueData []*Webhook
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersWebhookListEnvelope(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookListEnvelope{}
		var expected []*Webhook
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookListEnvelope{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookListEnvelope
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

}

func TestSettersMarkExplicitWebhookListEnvelope(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookListEnvelope{}
		var fernTestValueData []*Webhook

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingWebhook(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &Webhook{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled Webhook
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj Webhook
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj Webhook
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWebhookDeliveriesEnvelope(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDeliveriesEnvelope{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookDeliveriesEnvelope
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookDeliveriesEnvelope
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WebhookDeliveriesEnvelope
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWebhookDelivery(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookDelivery{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookDelivery
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookDelivery
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WebhookDelivery
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWebhookEnvelope(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookEnvelope{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookEnvelope
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookEnvelope
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WebhookEnvelope
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingWebhookListEnvelope(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &WebhookListEnvelope{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled WebhookListEnvelope
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj WebhookListEnvelope
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj WebhookListEnvelope
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringWebhook(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &Webhook{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWebhookDeliveriesEnvelope(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookDeliveriesEnvelope{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDeliveriesEnvelope
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWebhookDelivery(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookDelivery{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWebhookEnvelope(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookEnvelope{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookEnvelope
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringWebhookListEnvelope(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookListEnvelope{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookListEnvelope
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesWebhook(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &Webhook{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *Webhook
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWebhookDeliveriesEnvelope(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookDeliveriesEnvelope{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDeliveriesEnvelope
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWebhookDelivery(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookDelivery{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookDelivery
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWebhookEnvelope(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookEnvelope{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookEnvelope
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesWebhookListEnvelope(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &WebhookListEnvelope{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *WebhookListEnvelope
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
