// Code generated by Fern. DO NOT EDIT.

package activity_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	polytomic "github.com/polytomic/polytomic-go/v25"
	client "github.com/polytomic/polytomic-go/v25/client"
	option "github.com/polytomic/polytomic-go/v25/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestActivityListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &polytomic.ActivityListRequest{
		StartTime: polytomic.MustParseDateTime(
			"2024-01-15T09:30:00Z",
		),
		EndTime: polytomic.MustParseDateTime(
			"2024-01-15T09:30:00Z",
		),
		Limit: polytomic.Int(
			1,
		),
		PageToken: polytomic.String(
			"page_token",
		),
		Order: polytomic.ActivityListRequestOrderAsc.Ptr(),
		HarborID: []*string{
			polytomic.String(
				"248df4b7-aa70-47b8-a036-33ac447e668d",
			),
		},
		EventType: []*string{
			polytomic.String(
				"event_type",
			),
		},
		Outcome: []*string{
			polytomic.String(
				"outcome",
			),
		},
		OperationID: []*string{
			polytomic.String(
				"248df4b7-aa70-47b8-a036-33ac447e668d",
			),
		},
		SessionID: []*string{
			polytomic.String(
				"248df4b7-aa70-47b8-a036-33ac447e668d",
			),
		},
		ActorID: []*string{
			polytomic.String(
				"248df4b7-aa70-47b8-a036-33ac447e668d",
			),
		},
		CredentialID: []*string{
			polytomic.String(
				"248df4b7-aa70-47b8-a036-33ac447e668d",
			),
		},
		ConnectionID: []*string{
			polytomic.String(
				"248df4b7-aa70-47b8-a036-33ac447e668d",
			),
		},
	}
	_, invocationErr := client.Activity.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestActivityListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestActivityListWithWireMock", "GET", "/api/organization/harbor-activity", map[string]interface{}{"start_time": "2024-01-15T09:30:00.000Z", "end_time": "2024-01-15T09:30:00.000Z", "limit": "1", "page_token": "page_token", "order": "asc", "harbor_id": "248df4b7-aa70-47b8-a036-33ac447e668d", "event_type": "event_type", "outcome": "outcome", "operation_id": "248df4b7-aa70-47b8-a036-33ac447e668d", "session_id": "248df4b7-aa70-47b8-a036-33ac447e668d", "actor_id": "248df4b7-aa70-47b8-a036-33ac447e668d", "credential_id": "248df4b7-aa70-47b8-a036-33ac447e668d", "connection_id": "248df4b7-aa70-47b8-a036-33ac447e668d"}, 1)
}

func TestActivityGetSessionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &polytomic.ActivityGetSessionRequest{
		Limit: polytomic.Int(
			1,
		),
		PageToken: polytomic.String(
			"page_token",
		),
		Order: polytomic.ActivityGetSessionRequestOrderAsc.Ptr(),
	}
	_, invocationErr := client.Activity.GetSession(
		context.TODO(),
		"248df4b7-aa70-47b8-a036-33ac447e668d",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestActivityGetSessionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestActivityGetSessionWithWireMock", "GET", "/api/organization/harbor-activity/sessions/248df4b7-aa70-47b8-a036-33ac447e668d", map[string]interface{}{"limit": "1", "page_token": "page_token", "order": "asc"}, 1)
}

func TestActivityGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	_, invocationErr := client.Activity.Get(
		context.TODO(),
		"248df4b7-aa70-47b8-a036-33ac447e668d",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestActivityGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestActivityGetWithWireMock", "GET", "/api/organization/harbor-activity/248df4b7-aa70-47b8-a036-33ac447e668d", nil, 1)
}
