// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	polytomic "github.com/polytomic/polytomic-go"
	executions "github.com/polytomic/polytomic-go/bulksync/executions"
	schedules "github.com/polytomic/polytomic-go/bulksync/schedules"
	schemas "github.com/polytomic/polytomic-go/bulksync/schemas"
	core "github.com/polytomic/polytomic-go/core"
	internal "github.com/polytomic/polytomic-go/internal"
	option "github.com/polytomic/polytomic-go/option"
)

type Client struct {
	WithRawResponse *RawClient
	Executions      *executions.Client
	Schemas         *schemas.Client
	Schedules       *schedules.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Executions:      executions.NewClient(options),
		Schemas:         schemas.NewClient(options),
		Schedules:       schedules.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) List(
	ctx context.Context,
	request *polytomic.BulkSyncListRequest,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncListEnvelope, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new Bulk Sync from a source to a destination (data warehouse, database, or cloud storage bucket like S3).
//
// Bulk Syncs are used for the ELT pattern (Extract, Load, and Transform), where you want to sync un-transformed data to your data warehouses, databases, or cloud storage buckets like S3.
//
// All of the functionality described in [the product
// documentation](https://docs.polytomic.com/docs/bulk-syncs) is configurable via
// the API.
//
// Sample code examples:
//
// - [Bulk sync (ELT) from Salesforce to S3](https://apidocs.polytomic.com/guides/code-examples/bulk-sync-elt-from-salesforce-to-s-3)
// - [Bulk sync (ELT) from Salesforce to Snowflake](https://apidocs.polytomic.com/guides/code-examples/bulk-sync-elt-from-salesforce-to-snowflake)
// - [Bulk sync (ELT) from HubSpot to PostgreSQL](https://apidocs.polytomic.com/guides/code-examples/bulk-sync-elt-from-hub-spot-to-postgre-sql)
//
// ## Connection specific configuration
//
// The `destination_configuration` is integration-specific configuration for the
// selected bulk sync destination. This includes settings such as the output schema
// and is required when creating a new sync.
//
// The `source_configuration` is optional. It allows configuration for how
// Polytomic reads data from the source connection. This will not be available for
// integrations that do not support additional configuration.
//
// Consult the [connection configurations](https://apidocs.polytomic.com/2024-02-08/guides/configuring-your-connections/overview)
// to see configurations for particular integrations (for example, [here](https://apidocs.polytomic.com/2024-02-08/guides/configuring-your-connections/connections/postgre-sql#source-1) is the available source configuration for the PostgreSQL bulk sync source).
func (c *Client) Create(
	ctx context.Context,
	request *polytomic.CreateBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	id string,
	request *polytomic.BulkSyncGetRequest,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// > 📘 Updating schemas
// >
// > Schema updates can be performed using the [Update Bulk Sync Schemas](https://apidocs.polytomic.com/api-reference/bulk-sync/schemas/patch) endpoint.
func (c *Client) Update(
	ctx context.Context,
	id string,
	request *polytomic.UpdateBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Remove(
	ctx context.Context,
	id string,
	request *polytomic.BulkSyncRemoveRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Remove(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) Activate(
	ctx context.Context,
	id string,
	request *polytomic.ActivateSyncInput,
	opts ...option.RequestOption,
) (*polytomic.ActivateSyncEnvelope, error) {
	response, err := c.WithRawResponse.Activate(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Cancel(
	ctx context.Context,
	// The active execution of this bulk sync ID will be cancelled.
	id string,
	opts ...option.RequestOption,
) (*polytomic.CancelBulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Cancel(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Start(
	ctx context.Context,
	id string,
	request *polytomic.StartBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncExecutionEnvelope, error) {
	response, err := c.WithRawResponse.Start(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetStatus(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncStatusEnvelope, error) {
	response, err := c.WithRawResponse.GetStatus(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetSource(
	ctx context.Context,
	id string,
	request *polytomic.BulkSyncGetSourceRequest,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncSourceEnvelope, error) {
	response, err := c.WithRawResponse.GetSource(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetDestination(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncDestEnvelope, error) {
	response, err := c.WithRawResponse.GetDestination(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
