// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"

	polytomic "github.com/polytomic/polytomic-go/v24"
	executions "github.com/polytomic/polytomic-go/v24/bulksync/executions"
	schedules "github.com/polytomic/polytomic-go/v24/bulksync/schedules"
	schemas "github.com/polytomic/polytomic-go/v24/bulksync/schemas"
	core "github.com/polytomic/polytomic-go/v24/core"
	internal "github.com/polytomic/polytomic-go/v24/internal"
	option "github.com/polytomic/polytomic-go/v24/option"
)

type Client struct {
	WithRawResponse *RawClient
	Executions      *executions.Client
	Schemas         *schemas.Client
	Schedules       *schedules.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Executions:      executions.NewClient(options),
		Schemas:         schemas.NewClient(options),
		Schedules:       schedules.NewClient(options),
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Lists bulk syncs in the caller's organization.
//
// Results are returned as a single `data` array. This version of the endpoint
// supports the `active` filter but does not support cursor pagination, `limit`,
// or `page_token` query parameters.
//
// If you need a cursor-paginated bulk sync list, use API version `2025-09-18` or
// later.
//
// > 📘 To retrieve a specific sync, use
// > [`GET /api/bulk/syncs/{id}`](../../../api-reference/bulk-sync/get)
// > instead of filtering the list client-side.
func (c *Client) List(
	ctx context.Context,
	request *polytomic.ListBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.V2BulkSyncListEnvelope, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new bulk sync from a source connection to a destination connection.
//
// Bulk syncs are used for the ELT pattern (Extract, Load, and Transform), where you want to sync un-transformed data to your data warehouses, databases, or cloud storage buckets like S3.
//
// All of the functionality described in [the product
// documentation](https://docs.polytomic.com/docs/bulk-syncs) is configurable via
// the API.
//
// Sample code examples:
//
// - [Bulk sync (ELT) from Salesforce to S3](../../../guides/code-examples/bulk-sync-elt-from-salesforce-to-s-3)
// - [Bulk sync (ELT) from Salesforce to Snowflake](../../../guides/code-examples/bulk-sync-elt-from-salesforce-to-snowflake)
// - [Bulk sync (ELT) from HubSpot to PostgreSQL](../../../guides/code-examples/bulk-sync-elt-from-hub-spot-to-postgre-sql)
//
// ## Connection specific configuration
//
// The `destination_configuration` is integration-specific configuration for the
// selected bulk sync destination. This includes settings such as the output schema
// and is required when creating a new sync.
//
// The `source_configuration` is optional. It allows configuration for how
// Polytomic reads data from the source connection. This will not be available for
// integrations that do not support additional configuration.
//
// Consult the [connection configurations](../../../guides/configuring-your-connections/overview)
// to see configurations for particular integrations (for example, [here](../../../guides/configuring-your-connections/connections/postgre-sql#source-1) is the available source configuration for the PostgreSQL bulk sync source).
//
// ## Defaults and selection behavior
//
// If `schemas` is omitted, the sync is created with all available source schemas
// selected. Pass `schemas` explicitly if you want the initial sync to include
// only a subset of tables or objects.
//
// Schedule times are interpreted in UTC.
//
// When omitted, automatic discovery defaults are conservative:
//
//   - `automatically_add_new_objects` defaults to not enabling newly discovered
//     source objects automatically.
//   - `automatically_add_new_fields` defaults to enabling newly discovered fields
//     on already selected objects.
//   - `normalize_names` defaults to enabled.
func (c *Client) Create(
	ctx context.Context,
	request *polytomic.V2CreateBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.V2BulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a single bulk sync by ID.
//
// The response includes the sync's top-level configuration — source, destination,
// schedules, and discovery settings.
//
//   - To check whether the sync is running and see the most-recent execution result,
//     use [`GET /api/bulk/syncs/{id}/status`](../../../../api-reference/bulk-sync/get-status).
//   - To inspect which schemas are selected and how they are configured, use
//     [`GET /api/bulk/syncs/{id}/schemas`](../../../../api-reference/bulk-sync/schemas/list).
func (c *Client) Get(
	ctx context.Context,
	id string,
	request *polytomic.GetBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.V2BulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates an existing bulk sync's top-level configuration.
//
// Updating a bulk sync is a **full replacement** of the sync's top-level
// configuration. Every field in the request body is written to the sync; any
// field you omit is cleared or reset to its default value.
//
// To make a partial change — for example, toggling `active` or swapping a
// schedule — fetch the current sync with
// [`GET /api/bulk/syncs/{id}`](../../../../api-reference/bulk-sync/get),
// modify the fields you want to change, and send the complete object back in
// the update request.
//
// Updates to `active`, `schedules`, and `policies` take effect immediately.
// Changes to source or destination configuration take effect on the sync's
// next execution.
//
// Because omitted fields are reset to their defaults, the discovery and
// naming options behave the same as on create when left out:
//
//   - `automatically_add_new_objects` resets to not enabling newly discovered
//     source objects automatically.
//   - `automatically_add_new_fields` resets to enabling newly discovered
//     fields on already selected objects.
//   - `normalize_names` resets to enabled.
//
// Send the existing values explicitly if you want to preserve a non-default or
// non-empty setting, including schema and field selections.
//
// > 📘 Updating schemas
// >
// > Schema updates are not performed through this endpoint. Use the
// > [Update Bulk Sync Schemas](../../../../api-reference/bulk-sync/schemas/patch)
// > endpoint to change a subset of schemas, or
// > [Update Bulk Sync Schema](../../../../api-reference/bulk-sync/schemas/update)
// > to replace a single schema's configuration.
func (c *Client) Update(
	ctx context.Context,
	id string,
	request *polytomic.V2UpdateBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.V2BulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes a bulk sync, cancelling any running executions.
//
// Any execution that is currently running is cancelled before the sync record is
// removed.
//
// > 🚧 All associated schedules, schema configurations, and execution history are
// > deleted along with the sync.
func (c *Client) Remove(
	ctx context.Context,
	id string,
	request *polytomic.RemoveBulkSyncRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Remove(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Sets whether a bulk sync is active.
//
// Only active syncs are eligible to execute on their configured schedule.
// Deactivating a sync prevents future scheduled runs and requests cancellation of
// any execution that is currently in progress.
//
// > 📘 To start or stop a running execution directly, use
// > [`POST /api/bulk/syncs/{id}/executions`](../../../../../api-reference/bulk-sync/start)
// > or
// > [`POST /api/bulk/syncs/{id}/cancel`](../../../../../api-reference/bulk-sync/cancel).
func (c *Client) Activate(
	ctx context.Context,
	id string,
	request *polytomic.V2ActivateSyncInput,
	opts ...option.RequestOption,
) (*polytomic.V2ActivateSyncEnvelope, error) {
	response, err := c.WithRawResponse.Activate(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Requests cancellation of any running executions on a bulk sync.
//
// Cancellation is asynchronous. A successful response means the cancellation
// signal has been queued; the running execution continues until the signal is
// processed. Poll `GET /api/bulk/syncs/{id}/status` until the current execution
// reaches a terminal state (`completed`, `canceled`, or `failed`) to confirm
// cancellation has taken effect.
func (c *Client) Cancel(
	ctx context.Context,
	// The active execution of this bulk sync ID will be cancelled.
	id string,
	opts ...option.RequestOption,
) (*polytomic.V2CancelBulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Cancel(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Starts a new execution of a bulk sync.
//
// This endpoint returns the execution record immediately after the run is queued
// or started. Use the execution ID with the bulk-sync execution endpoints if you
// need to monitor progress in detail.
//
// ## Execution modes
//
// - Set `test=true` to validate the sync without writing to the destination.
// - Use `resync_mode` for destructive or full-refresh style reruns.
// - `test` and `resync_mode` are mutually exclusive.
//
// The legacy `resync` boolean is no longer accepted on this v5 endpoint. Send
// `resync_mode` instead.
//
// If another execution is already running, the endpoint returns `409 Conflict`.
func (c *Client) Start(
	ctx context.Context,
	// Unique identifier of the bulk sync.
	id string,
	request *polytomic.V3StartBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.V3BulkSyncExecutionEnvelope, error) {
	response, err := c.WithRawResponse.Start(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the current status of a bulk sync.
//
// The response includes the sync's current active/inactive state together with
// information about the most recent execution — its status, start time, and any
// errors — making this endpoint well-suited for health checks and monitoring
// dashboards.
//
// For the complete execution history, use
// [`GET /api/bulk/syncs/{id}/executions`](../../../../../api-reference/bulk-sync/executions/list).
// For the full details of a specific run, including per-schema breakdowns, use
// [`GET /api/bulk/syncs/{id}/executions/{exec_id}`](../../../../../api-reference/bulk-sync/executions/get).
func (c *Client) GetStatus(
	ctx context.Context,
	// Unique identifier of the bulk sync.
	id string,
	opts ...option.RequestOption,
) (*polytomic.V3BulkSyncStatusEnvelope, error) {
	response, err := c.WithRawResponse.GetStatus(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists the schemas (tables or objects) available on a connection for use as a bulk sync source, optionally including per-schema field details.
//
// The response reflects what the
// connection currently has cached; if the upstream source has changed, trigger
// a refresh first with
// [`POST /api/connections/{id}/schemas/refresh`](../../../../../api-reference/schemas/refresh).
//
// These are the schemas available for selection, not the schemas already
// configured on any particular sync. To inspect schemas on a running sync, use
// [`GET /api/bulk/syncs/{id}/schemas`](../../../../../api-reference/bulk-sync/schemas/list).
//
// Pass `include_fields=true` to receive per-schema field details in a single call.
// Omit it when you only need the schema list, as field enumeration can be slow for
// large sources.
func (c *Client) GetSource(
	ctx context.Context,
	// Unique identifier of the connection.
	id string,
	request *polytomic.GetSourceBulkSyncRequest,
	opts ...option.RequestOption,
) (*polytomic.V3BulkSyncSourceEnvelope, error) {
	response, err := c.WithRawResponse.GetSource(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Describes the destination configuration schema a connection accepts when used as a bulk sync destination.
//
// The response is a JSON Schema object describing the shape of the
// `destination_configuration` field you must supply when
// [creating](../../../../../api-reference/bulk-sync/create) or
// [updating](../../../../../api-reference/bulk-sync/update) a bulk sync that uses this
// connection as its destination. Required fields vary by connection type.
//
// > 📘 Fetch this endpoint once per connection type rather than once per sync.
// > The configuration schema is the same for all syncs sharing the same
// > destination connection.
func (c *Client) GetDestination(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*polytomic.V2BulkSyncDestEnvelope, error) {
	response, err := c.WithRawResponse.GetDestination(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
