// Code generated by Fern. DO NOT EDIT.

package targets

import (
	context "context"

	polytomic "github.com/polytomic/polytomic-go/v24"
	core "github.com/polytomic/polytomic-go/v24/core"
	internal "github.com/polytomic/polytomic-go/v24/internal"
	modelsync "github.com/polytomic/polytomic-go/v24/modelsync"
	option "github.com/polytomic/polytomic-go/v24/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns target metadata for a connection.
//
// > 🚧 Deprecated
// >
// > Use `GET /api/connections/{id}/modelsync/targetobjects` instead.
func (c *Client) GetTarget(
	ctx context.Context,
	// Unique identifier of the connection.
	id string,
	request *modelsync.GetTargetTargetsRequest,
	opts ...option.RequestOption,
) (*polytomic.V2GetConnectionMetaEnvelope, error) {
	response, err := c.WithRawResponse.GetTarget(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the fields of a specific target object on a connection.
//
// Pass the target object identifier to retrieve the fields available for
// mapping on that object. These are the destination fields you can reference
// when configuring field mappings in a model sync.
//
// > 📘 To list available target objects and their identifiers, use
// > [`GET /api/connections/{id}/modelsync/targetobjects`](../../../../../../api-reference/model-sync/targets/list).
//
// Fields returned here reflect the connection's current cached state. If the
// upstream object schema has changed, trigger a schema refresh with
// [`POST /api/connections/{id}/schemas/refresh`](../../../../../../api-reference/schemas/refresh)
// before calling this endpoint.
func (c *Client) GetTargetFields(
	ctx context.Context,
	// Unique identifier of the connection.
	id string,
	request *modelsync.GetTargetFieldsTargetsRequest,
	opts ...option.RequestOption,
) (*polytomic.V2TargetResponseEnvelope, error) {
	response, err := c.WithRawResponse.GetTargetFields(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Lists the target objects available on a connection for use as a model sync destination.
//
// If the connection supports creating new destinations, the `target_creation`
// object will contain information on what properties are required to create the
// target.
//
// Target creation properties are all string values; the `enum` flag indicates if
// the property has a fixed set of valid values. When `enum` is `true`, the [Target
// Creation Property
// Values](../../../../../api-reference/model-sync/targets/get-create-property)
// endpoint can be used to retrieve the valid values.
//
// ## Sync modes
//
// The sync mode determines which records are written to the destination for a
// model sync. The `modes` array for a target object defines the `id` along with
// what operations the mode supports.
func (c *Client) List(
	ctx context.Context,
	id string,
	opts ...option.RequestOption,
) (*polytomic.V4TargetObjectsResponseEnvelope, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the valid values for a target-creation property on a connection that supports creating new target objects.
//
// Connections which support creating new sync target objects (destinations) will
// return `target_creation` with their [target object list](../../../../../../../api-reference/model-sync/targets/list). This endpoint
// will return possible values for properties where `enum` is `true`.
//
// If the connection does not support creating new target objects, an HTTP 404 will
// be returned.
//
// The `values` array lists the valid options (and labels) for the property. Each
// member of the `values` array has a `label` and `value`. For exaample,
//
// ```json
//
//	{
//	  "data": [
//	    {
//	      "id": "account",
//	      "title": "Account ID",
//	      "enum": true,
//	      "values": [
//	        {
//	          "value": "1234567::urn:li:organization:987654",
//	          "label": "Polytomic Inc. (1234567)"
//	        }
//	      ]
//	    }
//	  ]
//	}
//
// ```
//
// The `value` for the selected option should be passed when [creating a
// sync](../../../../../../../api-reference/model-sync/create).
func (c *Client) GetCreateProperty(
	ctx context.Context,
	id string,
	property string,
	opts ...option.RequestOption,
) (*polytomic.V4TargetPropertyValuesEnvelope, error) {
	response, err := c.WithRawResponse.GetCreateProperty(
		ctx,
		id,
		property,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
