// Code generated by Fern. DO NOT EDIT.

package executions

import (
	context "context"

	polytomic "github.com/polytomic/polytomic-go"
	bulksync "github.com/polytomic/polytomic-go/bulksync"
	core "github.com/polytomic/polytomic-go/core"
	internal "github.com/polytomic/polytomic-go/internal"
	option "github.com/polytomic/polytomic-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) ListStatus(
	ctx context.Context,
	request *bulksync.ExecutionsListStatusRequest,
	opts ...option.RequestOption,
) (*polytomic.ListBulkSyncExecutionStatusEnvelope, error) {
	response, err := c.WithRawResponse.ListStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) List(
	ctx context.Context,
	id string,
	request *bulksync.ExecutionsListRequest,
	opts ...option.RequestOption,
) (*polytomic.ListBulkSyncExecutionsEnvelope, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Get(
	ctx context.Context,
	id string,
	execId string,
	opts ...option.RequestOption,
) (*polytomic.BulkSyncExecutionEnvelope, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		id,
		execId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) Cancel(
	ctx context.Context,
	// The bulk sync ID.
	id string,
	// The execution ID to cancel.
	execId string,
	opts ...option.RequestOption,
) (*polytomic.CancelBulkSyncResponseEnvelope, error) {
	response, err := c.WithRawResponse.Cancel(
		ctx,
		id,
		execId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetLogs(
	ctx context.Context,
	syncId string,
	executionId string,
	opts ...option.RequestOption,
) (*polytomic.V4BulkSyncExecutionLogsEnvelope, error) {
	response, err := c.WithRawResponse.GetLogs(
		ctx,
		syncId,
		executionId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) ExportLogs(
	ctx context.Context,
	syncId string,
	executionId string,
	request *bulksync.ExecutionsExportLogsRequest,
	opts ...option.RequestOption,
) (*polytomic.V4ExportSyncLogsEnvelope, error) {
	response, err := c.WithRawResponse.ExportLogs(
		ctx,
		syncId,
		executionId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
