// This file was auto-generated by Fern from our API Definition.

package bulksync

import (
	polytomicgo "github.com/polytomic/polytomic-go"
)

type CreateScheduleRequest struct {
	Schedule *polytomicgo.V4BulkSyncScheduleAPI `json:"schedule,omitempty" url:"schedule,omitempty"`
}

type SchedulesDeleteRequest struct {
}

type SchedulesGetRequest struct {
}

type SchedulesListRequest struct {
}

type UpdateScheduleRequest struct {
	Schedule *polytomicgo.V4BulkSyncScheduleAPI `json:"schedule,omitempty" url:"schedule,omitempty"`
}
