// Code generated by Fern. DO NOT EDIT.

package webhooks_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	polytomic "github.com/polytomic/polytomic-go"
	client "github.com/polytomic/polytomic-go/client"
	option "github.com/polytomic/polytomic-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestWebhooksListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Webhooks.List(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksListWithWireMock", "GET", "/api/webhooks", nil, 1)
}

func TestWebhooksCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &polytomic.CreateWebhooksSchema{
		Endpoint: "https://example.com/webhook",
		Secret:   "secret",
	}
	_, invocationErr := client.Webhooks.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksCreateWithWireMock", "POST", "/api/webhooks", nil, 1)
}

func TestWebhooksGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Webhooks.Get(
		context.TODO(),
		"248df4b7-aa70-47b8-a036-33ac447e668d",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksGetWithWireMock", "GET", "/api/webhooks/248df4b7-aa70-47b8-a036-33ac447e668d", nil, 1)
}

func TestWebhooksUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &polytomic.UpdateWebhooksSchema{
		Endpoint: "https://example.com/webhook",
		Secret:   "secret",
	}
	_, invocationErr := client.Webhooks.Update(
		context.TODO(),
		"248df4b7-aa70-47b8-a036-33ac447e668d",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksUpdateWithWireMock", "PUT", "/api/webhooks/248df4b7-aa70-47b8-a036-33ac447e668d", nil, 1)
}

func TestWebhooksRemoveWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	invocationErr := client.Webhooks.Remove(
		context.TODO(),
		"248df4b7-aa70-47b8-a036-33ac447e668d",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksRemoveWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksRemoveWithWireMock", "DELETE", "/api/webhooks/248df4b7-aa70-47b8-a036-33ac447e668d", nil, 1)
}

func TestWebhooksDisableWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Webhooks.Disable(
		context.TODO(),
		"248df4b7-aa70-47b8-a036-33ac447e668d",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksDisableWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksDisableWithWireMock", "POST", "/api/webhooks/248df4b7-aa70-47b8-a036-33ac447e668d/disable", nil, 1)
}

func TestWebhooksEnableWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Webhooks.Enable(
		context.TODO(),
		"248df4b7-aa70-47b8-a036-33ac447e668d",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestWebhooksEnableWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestWebhooksEnableWithWireMock", "POST", "/api/webhooks/248df4b7-aa70-47b8-a036-33ac447e668d/enable", nil, 1)
}
