// Code generated by Fern. DO NOT EDIT.

package queryrunner

import (
	context "context"

	polytomic "github.com/polytomic/polytomic-go/v25"
	core "github.com/polytomic/polytomic-go/v25/core"
	internal "github.com/polytomic/polytomic-go/v25/internal"
	option "github.com/polytomic/polytomic-go/v25/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.Version == nil {
		versionDefault := "2025-09-18"
		options.Version = &versionDefault
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Submits a query for asynchronous execution against the connection.
//
// This endpoint returns immediately with a query task ID. It does not wait for
// the query to finish. Poll [`GET /api/queries/{id}`](../../../../api-reference/query-runner/get-query) until `status`
// reaches `done` or `failed`.
//
// Only the user who created the query can fetch its results later. Query results
// are stored temporarily and may expire; use the `expires` field from the result
// endpoint to understand how long they will remain available.
//
// Example:
//
//	request := &polytomic.RunQueryRequest{
//	    Query: polytomic.String(
//	        "SELECT * FROM table",
//	    ),
//	}
//	client.QueryRunner.RunQuery(
//	    context.TODO(),
//	    "248df4b7-aa70-47b8-a036-33ac447e668d",
//	    request,
//	)
func (c *Client) RunQuery(
	ctx context.Context,
	// Unique identifier of the connection to run the query against.
	connectionID string,
	request *polytomic.RunQueryRequest,
	opts ...option.IdempotentRequestOption,
) (*polytomic.RunQueryEnvelope, error) {
	response, err := c.WithRawResponse.RunQuery(
		ctx,
		connectionID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Fetches the latest status for a submitted query and, once complete, returns fields and paginated results.
//
// This endpoint is the second step of the query-runner flow. First call
// [`POST /api/connections/{connection_id}/query`](../../../api-reference/query-runner/run-query),
// then poll this endpoint with the returned ID.
//
// Results may be paginated across multiple blobs. When that happens, use the
// opaque `links.next` and `links.previous` URLs exactly as returned. Do not try to
// construct the `page` token yourself.
//
// If the query is still running, the response may include only status metadata.
// If the task is complete but the caller is not the same user that created it,
// the endpoint returns `404`.
//
// Example:
//
//	request := &polytomic.QueryRunnerGetQueryRequest{
//	    Page: polytomic.String(
//	        "page",
//	    ),
//	}
//	client.QueryRunner.GetQuery(
//	    context.TODO(),
//	    "248df4b7-aa70-47b8-a036-33ac447e668d",
//	    request,
//	)
func (c *Client) GetQuery(
	ctx context.Context,
	// Unique identifier of the query task, as returned by POST /api/connections/{connection_id}/query.
	id string,
	request *polytomic.QueryRunnerGetQueryRequest,
	opts ...option.RequestOption,
) (*polytomic.QueryResultsEnvelope, error) {
	response, err := c.WithRawResponse.GetQuery(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
