// Code generated by Fern. DO NOT EDIT.

package queryrunner

import (
	context "context"
	http "net/http"

	polytomic "github.com/polytomic/polytomic-go/v24"
	core "github.com/polytomic/polytomic-go/v24/core"
	internal "github.com/polytomic/polytomic-go/v24/internal"
	option "github.com/polytomic/polytomic-go/v24/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) RunQuery(
	ctx context.Context,
	// Unique identifier of the connection to run the query against.
	connectionID string,
	request *polytomic.V4RunQueryRequest,
	opts ...option.RequestOption,
) (*core.Response[*polytomic.V4RunQueryEnvelope], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.polytomic.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/connections/%v/query",
		connectionID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *polytomic.V4RunQueryEnvelope
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(polytomic.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*polytomic.V4RunQueryEnvelope]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetQuery(
	ctx context.Context,
	// Unique identifier of the query task, as returned by POST /api/connections/{connection_id}/query.
	id string,
	request *polytomic.GetQueryQueryRunnerRequest,
	opts ...option.RequestOption,
) (*core.Response[*polytomic.V4QueryResultsEnvelope], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://app.polytomic.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/queries/%v",
		id,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *polytomic.V4QueryResultsEnvelope
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(polytomic.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*polytomic.V4QueryResultsEnvelope]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
