// Code generated by Fern. DO NOT EDIT.

package permissions

import (
	json "encoding/json"
	v24 "github.com/polytomic/polytomic-go/v24"
	internal "github.com/polytomic/polytomic-go/v24/internal"
	big "math/big"
)

var (
	v2CreatePolicyRequestFieldName           = big.NewInt(1 << 0)
	v2CreatePolicyRequestFieldOrganizationID = big.NewInt(1 << 1)
	v2CreatePolicyRequestFieldPolicyActions  = big.NewInt(1 << 2)
)

type V2CreatePolicyRequest struct {
	Name           string                `json:"name" url:"-"`
	OrganizationID *string               `json:"organization_id,omitempty" url:"-"`
	PolicyActions  []*v24.V2PolicyAction `json:"policy_actions,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V2CreatePolicyRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2CreatePolicyRequest) SetName(name string) {
	v.Name = name
	v.require(v2CreatePolicyRequestFieldName)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2CreatePolicyRequest) SetOrganizationID(organizationID *string) {
	v.OrganizationID = organizationID
	v.require(v2CreatePolicyRequestFieldOrganizationID)
}

// SetPolicyActions sets the PolicyActions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2CreatePolicyRequest) SetPolicyActions(policyActions []*v24.V2PolicyAction) {
	v.PolicyActions = policyActions
	v.require(v2CreatePolicyRequestFieldPolicyActions)
}

func (v *V2CreatePolicyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler V2CreatePolicyRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*v = V2CreatePolicyRequest(body)
	return nil
}

func (v *V2CreatePolicyRequest) MarshalJSON() ([]byte, error) {
	type embed V2CreatePolicyRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	v2UpdatePolicyRequestFieldName           = big.NewInt(1 << 0)
	v2UpdatePolicyRequestFieldOrganizationID = big.NewInt(1 << 1)
	v2UpdatePolicyRequestFieldPolicyActions  = big.NewInt(1 << 2)
)

type V2UpdatePolicyRequest struct {
	Name           string                `json:"name" url:"-"`
	OrganizationID *string               `json:"organization_id,omitempty" url:"-"`
	PolicyActions  []*v24.V2PolicyAction `json:"policy_actions,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *V2UpdatePolicyRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2UpdatePolicyRequest) SetName(name string) {
	v.Name = name
	v.require(v2UpdatePolicyRequestFieldName)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2UpdatePolicyRequest) SetOrganizationID(organizationID *string) {
	v.OrganizationID = organizationID
	v.require(v2UpdatePolicyRequestFieldOrganizationID)
}

// SetPolicyActions sets the PolicyActions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *V2UpdatePolicyRequest) SetPolicyActions(policyActions []*v24.V2PolicyAction) {
	v.PolicyActions = policyActions
	v.require(v2UpdatePolicyRequestFieldPolicyActions)
}

func (v *V2UpdatePolicyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler V2UpdatePolicyRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*v = V2UpdatePolicyRequest(body)
	return nil
}

func (v *V2UpdatePolicyRequest) MarshalJSON() ([]byte, error) {
	type embed V2UpdatePolicyRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}
