// This file was auto-generated by Fern from our API Definition.

package modelsync

type TargetsGetCreatePropertyRequest struct {
}

type TargetsGetTargetRequest struct {
	Type   *string `json:"-" url:"type,omitempty"`
	Search *string `json:"-" url:"search,omitempty"`
}

type TargetsGetTargetFieldsRequest struct {
	Target  string `json:"-" url:"target"`
	Refresh *bool  `json:"-" url:"refresh,omitempty"`
}

type TargetsListRequest struct {
}
