// Code generated by Fern. DO NOT EDIT.

package modelsync

import (
	big "math/big"
)

var (
	targetsGetTargetRequestFieldType   = big.NewInt(1 << 0)
	targetsGetTargetRequestFieldSearch = big.NewInt(1 << 1)
)

type TargetsGetTargetRequest struct {
	Type   *string `json:"-" url:"type,omitempty"`
	Search *string `json:"-" url:"search,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TargetsGetTargetRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TargetsGetTargetRequest) SetType(type_ *string) {
	t.Type = type_
	t.require(targetsGetTargetRequestFieldType)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TargetsGetTargetRequest) SetSearch(search *string) {
	t.Search = search
	t.require(targetsGetTargetRequestFieldSearch)
}

var (
	targetsGetTargetFieldsRequestFieldTarget  = big.NewInt(1 << 0)
	targetsGetTargetFieldsRequestFieldRefresh = big.NewInt(1 << 1)
)

type TargetsGetTargetFieldsRequest struct {
	Target  string `json:"-" url:"target"`
	Refresh *bool  `json:"-" url:"refresh,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TargetsGetTargetFieldsRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTarget sets the Target field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TargetsGetTargetFieldsRequest) SetTarget(target string) {
	t.Target = target
	t.require(targetsGetTargetFieldsRequestFieldTarget)
}

// SetRefresh sets the Refresh field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TargetsGetTargetFieldsRequest) SetRefresh(refresh *bool) {
	t.Refresh = refresh
	t.require(targetsGetTargetFieldsRequestFieldRefresh)
}
